var searchData=
[
  ['changeorder',['ChangeOrder',['../struct_feel_1_1_dubiner_traits_1_1_change_order.html',1,'Feel::DubinerTraits']]],
  ['changeorder',['ChangeOrder',['../struct_feel_1_1_legendre_traits_1_1_change_order.html',1,'Feel::LegendreTraits']]],
  ['changeorder',['ChangeOrder',['../struct_feel_1_1_boundary_adapted_traits_1_1_change_order.html',1,'Feel::BoundaryAdaptedTraits']]],
  ['changetag',['ChangeTag',['../struct_feel_1_1_lagrange_1_1_change_tag.html',1,'Feel::Lagrange']]],
  ['changetag',['ChangeTag',['../struct_feel_1_1_nedelec_1_1_change_tag.html',1,'Feel::Nedelec']]],
  ['changetag',['ChangeTag',['../struct_feel_1_1_raviart_thomas_1_1_change_tag.html',1,'Feel::RaviartThomas']]],
  ['changetag',['ChangeTag',['../struct_feel_1_1_crouzeix_raviart_1_1_change_tag.html',1,'Feel::CrouzeixRaviart']]],
  ['changevaluetype',['ChangeValueType',['../struct_feel_1_1_dubiner_traits_1_1_change_value_type.html',1,'Feel::DubinerTraits']]],
  ['changevaluetype',['ChangeValueType',['../struct_feel_1_1_legendre_traits_1_1_change_value_type.html',1,'Feel::LegendreTraits']]],
  ['changevaluetype',['ChangeValueType',['../struct_feel_1_1_boundary_adapted_traits_1_1_change_value_type.html',1,'Feel::BoundaryAdaptedTraits']]],
  ['clear_5fvalue',['clear_value',['../struct_feel_1_1clear__value.html',1,'Feel']]],
  ['cmpbareitem_3c_20bareedge_20_3e',['cmpBareItem&lt; BareEdge &gt;',['../struct_feel_1_1cmp_bare_item_3_01_bare_edge_01_4.html',1,'Feel']]],
  ['cmpbareitem_3c_20bareface_20_3e',['cmpBareItem&lt; BareFace &gt;',['../struct_feel_1_1cmp_bare_item_3_01_bare_face_01_4.html',1,'Feel']]],
  ['cmpbareitem_3c_20barepoint_20_3e',['cmpBareItem&lt; BarePoint &gt;',['../struct_feel_1_1cmp_bare_item_3_01_bare_point_01_4.html',1,'Feel']]],
  ['component',['Component',['../struct_feel_1_1_component.html',1,'Feel']]],
  ['componentpointevaluation',['ComponentPointEvaluation',['../class_feel_1_1functional_1_1_component_point_evaluation.html',1,'Feel::functional']]],
  ['componentspointsevaluation',['ComponentsPointsEvaluation',['../struct_feel_1_1functional_1_1_components_points_evaluation.html',1,'Feel::functional']]],
  ['compute_5faitken_5freturn',['compute_aitken_return',['../struct_feel_1_1compute__aitken__return.html',1,'Feel']]],
  ['compute_5feim_5freturn',['compute_eim_return',['../struct_feel_1_1detail_1_1compute__eim__return.html',1,'Feel::detail']]],
  ['compute_5fexporter_5freturn',['compute_exporter_return',['../struct_feel_1_1detail_1_1compute__exporter__return.html',1,'Feel::detail']]],
  ['computeintegrals',['ComputeIntegrals',['../struct_feel_1_1_c_r_b_1_1_compute_integrals.html',1,'Feel::CRB']]],
  ['computeintegralssquare',['ComputeIntegralsSquare',['../struct_feel_1_1_c_r_b_1_1_compute_integrals_square.html',1,'Feel::CRB']]],
  ['computenorml2incompositecase',['ComputeNormL2InCompositeCase',['../struct_feel_1_1_c_r_b_model_1_1_compute_norm_l2_in_composite_case.html',1,'Feel::CRBModel']]],
  ['computephi',['ComputePhi',['../struct_feel_1_1_c_r_b_1_1_compute_phi.html',1,'Feel::CRB']]],
  ['constant',['Constant',['../struct_feel_1_1math_1_1_constant.html',1,'Feel::math']]],
  ['constrainedpolynomialset',['ConstrainedPolynomialSet',['../class_feel_1_1_constrained_polynomial_set.html',1,'Feel']]],
  ['context',['Context',['../class_feel_1_1_geo_map_1_1_context.html',1,'Feel::GeoMap']]],
  ['context',['Context',['../class_feel_1_1_context.html',1,'Feel']]],
  ['context',['Context',['../class_feel_1_1_polynomial_set_1_1_context.html',1,'Feel::PolynomialSet']]],
  ['continuity_5fbase',['continuity_base',['../struct_feel_1_1detail_1_1continuity__base.html',1,'Feel::detail']]],
  ['continuous',['Continuous',['../class_feel_1_1_continuous.html',1,'Feel']]],
  ['convection',['Convection',['../class_convection.html',1,'']]],
  ['convectioncrb',['ConvectionCrb',['../class_convection_crb.html',1,'']]],
  ['convex',['Convex',['../struct_feel_1_1_dubiner_traits_1_1_convex.html',1,'Feel::DubinerTraits']]],
  ['convex',['Convex',['../struct_feel_1_1_tensorised_boundary_adapted_1_1_convex.html',1,'Feel::TensorisedBoundaryAdapted']]],
  ['convex',['Convex',['../struct_feel_1_1_legendre_traits_1_1_convex.html',1,'Feel::LegendreTraits']]],
  ['convex',['Convex',['../struct_feel_1_1_boundary_adapted_traits_1_1_convex.html',1,'Feel::BoundaryAdaptedTraits']]],
  ['convex',['Convex',['../class_feel_1_1_convex.html',1,'Feel']]],
  ['convex_3c_20dim_2c_20order_2c_20dim_20_3e',['Convex&lt; Dim, Order, Dim &gt;',['../class_feel_1_1_convex.html',1,'Feel']]],
  ['convexbase',['ConvexBase',['../class_feel_1_1_convex_base.html',1,'Feel']]],
  ['counter',['counter',['../class_feel_1_1details_1_1counter.html',1,'Feel::details']]],
  ['crb',['CRB',['../class_feel_1_1_c_r_b.html',1,'Feel']]],
  ['crbapp',['CRBApp',['../class_feel_1_1_c_r_b_app.html',1,'Feel']]],
  ['crbdb',['CRBDB',['../class_feel_1_1_c_r_b_d_b.html',1,'Feel']]],
  ['crbmodel',['CRBModel',['../class_feel_1_1_c_r_b_model.html',1,'Feel']]],
  ['crbmodeltrilinear',['CRBModelTrilinear',['../class_feel_1_1_c_r_b_model_trilinear.html',1,'Feel']]],
  ['crbscm',['CRBSCM',['../class_feel_1_1_c_r_b_s_c_m.html',1,'Feel']]],
  ['crbtrilinear',['CRBTrilinear',['../class_feel_1_1_c_r_b_trilinear.html',1,'Feel']]],
  ['crouzeixraviart',['CrouzeixRaviart',['../class_feel_1_1fem_1_1_crouzeix_raviart.html',1,'Feel::fem']]],
  ['crouzeixraviart',['CrouzeixRaviart',['../class_feel_1_1_crouzeix_raviart.html',1,'Feel']]],
  ['crouzeixraviartdual',['CrouzeixRaviartDual',['../class_feel_1_1fem_1_1detail_1_1_crouzeix_raviart_dual.html',1,'Feel::fem::detail']]],
  ['crouzeixraviartdual_3c_20mpl_3a_3aif_5f_3c_20mpl_3a_3abool_5f_3c_20convex_3c_20n_2c_201_2c_20n_20_3e_3a_3ais_5fsimplex_20_3e_2c_20mpl_3a_3aidentity_3c_20feel_3a_3adetail_3a_3aorthonormalpolynomialset_3c_20n_2c_201_2c_20realdim_2c_20polysettype_2c_20t_2c_20convex_20_3e_20_3e_2c_20mpl_3a_3aidentity_3c_20fem_3a_3adetail_3a_3arannacherturekpolynomialset_3c_20n_2c_20polysettype_2c_20t_20_3e_20_3e_20_3e_3a_3atype_3a_3atype_2c_20pointsetequispaced_20_3e',['CrouzeixRaviartDual&lt; mpl::if_&lt; mpl::bool_&lt; Convex&lt; N, 1, N &gt;::is_simplex &gt;, mpl::identity&lt; Feel::detail::OrthonormalPolynomialSet&lt; N, 1, RealDim, PolySetType, T, Convex &gt; &gt;, mpl::identity&lt; fem::detail::RannacherTurekPolynomialSet&lt; N, PolySetType, T &gt; &gt; &gt;::type::type, PointSetEquiSpaced &gt;',['../class_feel_1_1fem_1_1detail_1_1_crouzeix_raviart_dual.html',1,'Feel::fem::detail']]]
];
