Feel++: Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity > Class Template Reference
Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity > Class Template Reference
#include <geomapinv.hpp>
Detailed Description
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex>
class Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >
handles the geometric inversion for a given (supposedly quite large) set of points
Author
Christophe Prud'homme
Public Types
Typedefs
typedef GeoMap< Dim, Order,
RealDim, T, Entity > gm_type
typedef gm_type::Inverse gic_type
typedef T value_type
Public Member Functions
Constructors, destructor
GeoMapInverse (value_type eps=1e-12)
GeoMapInverse (GeoMapInverse const &gmi)
virtual ~GeoMapInverse ()
Methods
void clear (void)
template<class CONT >
void addPoints (const CONT &c)
size_type nPoints (void) const
size_type addPoint (typename node< value_type >::type const &p)
void addPointWithId (typename node< value_type >::type const &p, size_type id, uint16_type comp)
void addPointWithId (boost::tuple< typename node< value_type >::type, size_type, uint16_type > const &p)
size_type pointsInBox (KDTree::points_type &ipts, typename node< value_type >::type const &min, typename node< value_type >::type const &max) const
Member Function Documentation
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> size_type Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::addPoint (typename node< value_type >::type const & p) inline
Add point p to the list of points.
References Feel::KDTree::addPoint().
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> template<class CONT > void Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::addPoints (const CONT & c) inline
Add the points contained in c to the list of points.
References Feel::KDTree::addPointWithId(), and Feel::KDTree::reserve().
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> void Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::addPointWithId (typename node< value_type >::type const & p, size_type id, uint16_type comp) inline
add new points in the kd-tree
if lid is equal to invalid_uint16_type_value then it means that it is of no use and will be ignore
References Feel::KDTree::addPointWithId().
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> void Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::addPointWithId (boost::tuple< typename node< value_type >::type, size_type, uint16_type > const & p) inline
add new points in the kd-tree
References Feel::KDTree::addPointWithId().
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> void Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::clear (void) inline
clear the kd-tree
References Feel::KDTree::clear().
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> size_type Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::nPoints (void) const inline
Returns
Number of points.
References Feel::KDTree::nPoints().
template<int Dim, int Order = 1, int RealDim = Dim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex> size_type Feel::GeoMapInverse< Dim, Order, RealDim, T, Entity >::pointsInBox (KDTree::points_type & ipts, typename node< value_type >::type const & min, typename node< value_type >::type const & max) const inline
Find all the points present in the box between min and max.
References Feel::KDTree::pointsInBox().
The documentation for this class was generated from the following file:
geomapinv.hpp