Feel++: Feel::vf::details::EvaluatorContext< CTX, ExprT > Class Template Reference
Feel::vf::details::EvaluatorContext< CTX, ExprT > Class Template Reference
#include <evaluatorcontext.hpp>
Detailed Description
template<typename CTX, typename ExprT>
class Feel::vf::details::EvaluatorContext< CTX, ExprT >
work class to evaluate expressions at sets of points
Author
Christophe Prud'homme
Public Member Functions
Constructors, destructor
EvaluatorContext (context_type const &ctx, expression_type const &__expr, GeomapStrategyType geomap_strategy)
EvaluatorContext (EvaluatorContext const &__vfi)
virtual ~EvaluatorContext ()
Operator overloads
element_type operator() () const
Accessors
expression_type const & expression () const
Typedefs
typedef ExprT expression_type
typedef expression_type::value_type value_type
typedef CTX context_type
typedef Eigen::Matrix
< value_type, Eigen::Dynamic, 1 > element_type
static const uint16_type imorder = 1
static const bool imIsPoly = true
Member Function Documentation
template<typename CTX, typename ExprT> expression_type const& Feel::vf::details::EvaluatorContext< CTX, ExprT >::expression () const inline
get the variational expression
Returns
the variational expression
template<typename CTX , typename ExprT > EvaluatorContext< CTX, ExprT >::element_type Feel::vf::details::EvaluatorContext< CTX, ExprT >::operator() () const
be careful there is no guarantee that the set of contexts will have the reference points. We should probably have a flag set by the programmer so that we don't have to re-create the expression context if the reference points are the same
References Feel::idedelements(), Feel::project(), and val().
The documentation for this class was generated from the following file:
evaluatorcontext.hpp