Feel++: Feel::Sound< Dim, Order > Class Template Reference
Feel::Sound< Dim, Order > Class Template Reference
Detailed Description
template<int Dim, int Order>
class Feel::Sound< Dim, Order >
Sound Solver using discontinous approximation spaces
solve on and on
Public Types
typedef boost::shared_ptr
< backend_type > backend_ptrtype
typedef Backend< double > backend_type
typedef bases< Lagrange< Order,
Scalar > > basis_type
typedef space_type::element_type element_type
typedef Simplex< Dim, 1, Dim > entity_type
typedef Exporter< mesh_type > export_type
typedef boost::shared_ptr
< mesh_type > mesh_ptr_type
typedef Mesh< entity_type > mesh_type
typedef p0_space_type::element_type p0_element_type
typedef FunctionSpace
< mesh_type, bases< Lagrange
< 0, Scalar > >, Discontinuous > p0_space_type
typedef boost::shared_ptr
< space_type > space_ptrtype
typedef FunctionSpace
< mesh_type, basis_type > space_type
typedef
backend_type::sparse_matrix_ptrtype sparse_matrix_ptrtype
typedef
backend_type::sparse_matrix_type sparse_matrix_type
typedef double value_type
typedef
backend_type::vector_ptrtype vector_ptrtype
typedef backend_type::vector_type vector_type
Public Member Functions
std::string name () const
return the name of the simget
void run ()
Sound (std::string const &name)
Public Member Functions inherited from Feel::Simget
Simget ()
virtual ~Simget ()
destructor
Simget & operator= (Simget const &o)
copy operator
mpi::communicator comm () const
po::variables_map const & vm () const
AboutData const & about () const
double meshSize () const
return the mesh size
double meshSizeInit () const
return the mesh size
int level () const
return the refinement level
ptree::ptree const & stats () const
return the statistics associated to the simget after calling run
ptree::ptree & stats ()
return the statistics associated to the simget after calling run
void setMeshSize (double h)
set the mesh size
void setMeshSizeInit (double h)
set the initial mesh size
void setLevel (int level)
set the refinment level if applicable
virtual void run (const double *X, unsigned long P, double *Y, unsigned long N)
void print (std::ostream &out, std::vector< ptree::ptree > &stats)
Static Public Attributes
static const uint16_type imOrder = 2*Order
Additional Inherited Members
Protected Member Functions inherited from Feel::Simget
Simget & changeRepository (boost::format fmt)
Protected Attributes inherited from Feel::Simget
int M_level
double M_meshSize
double M_meshSizeInit
ptree::ptree M_stats
Member Function Documentation
template<int Dim, int Order> void Feel::Sound< Dim, Order >::run () virtual
run the convergence test
backend
eigen solver
exporter to paraview or gmsh
Implements Feel::Simget.
References Feel::SolverEigen< T >::build(), Feel::Backend< T >::build(), Feel::elements(), Feel::integrate(), Feel::markedfaces(), Feel::Exporter< MeshType, N >::New(), and val().
The documentation for this class was generated from the following file:
sound.cpp