Feel++: Feel::Mesh1D< Shape > Class Template Reference
Feel::Mesh1D< Shape > Class Template Reference
#include <mesh1d.hpp>
Detailed Description
template<typename Shape>
class Feel::Mesh1D< Shape >
1D mesh class
// create a 1D mesh made of simplex of order 1
Mesh1D<Simplex<1,1> > mesh;
// create a 1D mesh made of simplex of order 2
Mesh1D<Simplex<1,2> > mesh;
Author
Christophe Prud'homme
See Also
Public Member Functions
Constructors, destructor
Mesh1D (WorldComm const &worldComm=Environment::worldComm())
Mesh1D (Mesh1D const &m)
~Mesh1D ()
Operator overloads
Mesh1D & operator= (Mesh1D const &m)
Accessors
bool isEmpty () const
size_type numElements () const
size_type numLocalFaces () const
size_type numLocalVertices () const
size_type numFaces () const
size_type numPoints () const
Methods
virtual void setWorldComm (WorldComm const &_worldComm)
virtual void clear ()
FEELPP_DEFINE_VISITABLE ()
Public Member Functions inherited from Feel::VisitableBase< R, CatchAll >
virtual return_type accept (VisitorBase &)=0
accept visitor: use S_DEFINE_VISITABLE() to redefine it
virtual return_type accept (VisitorBase *)=0
accept visitor: use S_DEFINE_VISITABLE() to redefine it
Public Member Functions inherited from Feel::MeshBase
MeshBase (WorldComm const &worldComm=Environment::worldComm())
MeshBase (MeshBase const &)
virtual ~MeshBase ()
MeshBase & operator= (MeshBase const &m)
bool isUpdatedForUse () const
size_type numVertices () const
uint16_type numberOfPartitions () const
bool isPartitioned () const
Context const & components () const
Context & components ()
virtual double measure () const =0
bool isParametric () const
void setNumberOfPartitions (uint16_type n)
void setNumVertices (size_type n)
void setComponents (size_type components=MESH_ALL_COMPONENTS)
void setParametric (bool x)
virtual void updateForUse ()=0
virtual void updateForUse (size_type components)
virtual void partition (const uint16_type n_parts)=0
WorldComm const & worldComm () const
void setWorldCommMeshBase (WorldComm const &_worldComm)
mpi::communicator const & comm () const
virtual void meshModified ()=0
void setSubMeshData (smd_ptrtype smd)
set sub mesh data
bool hasSubMeshData () const
smd_type::mesh_ptrtype subMesh () const
bool isSubMeshFrom (MeshBase const *m) const
bool isSubMeshFrom (boost::shared_ptr< MeshBase > m) const
bool isParentMeshOf (boost::shared_ptr< MeshBase > m) const
template<typename M >
bool isSameMesh (M const *m) const
template<typename M >
bool isSameMesh (boost::shared_ptr< M > m) const
template<typename M >
bool isRelatedTo (boost::shared_ptr< M > m) const
size_type subMeshToMesh (size_type id) const
size_type meshToSubMesh (size_type id) const
size_type subMeshToMesh (boost::shared_ptr< MeshBase > m, size_type id) const
size_type meshToSubMesh (boost::shared_ptr< MeshBase > m, size_type id) const
Protected Member Functions
void renumber ()
void updateEntitiesCoDimensionOnePermutation ()
void updateEntitiesCoDimensionTwo ()
Protected Member Functions inherited from Feel::MeshBase
virtual void check () const =0
virtual void checkAndFixPermutation ()=0
void setUpdatedForUse (bool u)
virtual void updateEntitiesCoDimensionOne ()=0
Friends
class boost::serialization::access
Typedefs
typedef VisitableBase::return_type return_type
typedef VisitableBase super_visitable
typedef MeshBase super
typedef Elements< Shape > super_elements
typedef
super_elements::elements_type elements_type
typedef
super_elements::element_type element_type
typedef
super_elements::element_iterator element_iterator
typedef
super_elements::element_const_iterator element_const_iterator
typedef
super_elements::update_element_neighbor_type update_element_neighbor_type
typedef Points< nRealDim > super_points
typedef super_points::points_type points_type
typedef super_points::point_type point_type
typedef Faces< typename
Shape::template shape
< 0, Shape::nOrder,
Shape::nRealDim >::type,
typename
super_elements::element_type > super_faces
typedef super_faces::faces_type faces_type
typedef super_faces::face_type face_type
typedef face_type edge_type
typedef super_faces super_edges
typedef
super_edges::marker_face_iterator marker_edge_iterator
typedef
super_edges::marker_face_const_iterator marker_edge_const_iterator
typedef Mesh1D< Shape > self_type
typedef boost::shared_ptr
< self_type > self_ptrtype
typedef
element_type::vertex_permutation_type vertex_permutation_type
typedef
element_type::edge_permutation_type edge_permutation_type
typedef super::face_processor_type face_processor_type
static const uint16_type nDim = Shape::nRealDim
static const uint16_type nRealDim = Shape::nRealDim
Additional Inherited Members
Public Types inherited from Feel::VisitableBase< R, CatchAll >
typedef R return_type
Public Types inherited from Feel::MeshBase
typedef boost::tuple
< size_type, size_type > face_processor_type
typedef SubMeshData smd_type
typedef boost::shared_ptr
< smd_type > smd_ptrtype
Static Protected Member Functions inherited from Feel::VisitableBase< R, CatchAll >
template<class T >
static return_type acceptImpl (T *visited, VisitorBase *guest)
Constructor & Destructor Documentation
template<typename Shape > Feel::Mesh1D< Shape >::Mesh1D (WorldComm const & worldComm = Environment::worldComm()) inline
default constructor
template<typename Shape > Feel::Mesh1D< Shape >::Mesh1D (Mesh1D< Shape > const & m) inline
copy constructor
template<typename Shape > Feel::Mesh1D< Shape >::~Mesh1D () inline
destructor
Member Function Documentation
template<typename Shape > virtual void Feel::Mesh1D< Shape >::clear () inline virtual
clear out all data from the mesh, isEmpty() should return true after a clear()
Reimplemented from Feel::MeshBase.
References Feel::elements(), Feel::faces(), Feel::Mesh1D< Shape >::isEmpty(), and Feel::points().
template<typename Shape > bool Feel::Mesh1D< Shape >::isEmpty () const inline
Returns
true if all containers are empty, false otherwise
template<typename Shape > size_type Feel::Mesh1D< Shape >::numElements () const inline virtual
Returns
the number of elements
Implements Feel::MeshBase.
References Feel::elements().
template<typename Shape > size_type Feel::Mesh1D< Shape >::numFaces () const inline virtual
Returns
the number of faces
Implements Feel::MeshBase.
References Feel::faces().
template<typename Shape > size_type Feel::Mesh1D< Shape >::numLocalFaces () const inline
Returns
the number of faces in an element
template<typename Shape > size_type Feel::Mesh1D< Shape >::numLocalVertices () const inline
Returns
the number of vertices in an element
template<typename Shape > size_type Feel::Mesh1D< Shape >::numPoints () const inline virtual
Returns
the number of points
Implements Feel::MeshBase.
References Feel::points().
template<typename Shape > void Feel::Mesh1D< Shape >::renumber () inline protected virtual
dummy implementation
See Also
Mesh
Implements Feel::MeshBase.
template<typename Shape > void Feel::Mesh1D< Shape >::updateEntitiesCoDimensionOnePermutation () inline protected
update permutation of entities of co-dimension 1
template<typename Shape > void Feel::Mesh1D< Shape >::updateEntitiesCoDimensionTwo () inline protected virtual
update the entities of co-dimension 2
Implements Feel::MeshBase.
The documentation for this class was generated from the following file:
mesh1d.hpp