Feel++: Feel::Stokes Class Reference
Feel::Stokes Class Reference
Detailed Description
solves the stokes equations
Public Types
typedef boost::shared_ptr
< backend_type > backend_ptrtype
typedef Backend< value_type > backend_type
typedef Lagrange< 0, Scalar > basis_l_type
typedef Lagrange< 1, Scalar > basis_p_type
typedef bases< basis_u_type,
basis_p_type > basis_type
typedef Lagrange< 2, Vectorial > basis_u_type
typedef Simplex< 2 > convex_type
typedef space_type::element_type element_type
typedef Exporter< mesh_type > export_type
typedef boost::shared_ptr
< mesh_type > mesh_ptrtype
typedef Mesh< convex_type > mesh_type
typedef boost::shared_ptr
< space_type > space_ptrtype
typedef FunctionSpace
< mesh_type, basis_type > space_type
typedef double value_type
Public Member Functions
FEELPP_DONT_INLINE void init ()
FEELPP_DONT_INLINE void run ()
Public Member Functions inherited from Feel::Simget
Simget ()
virtual ~Simget ()
destructor
Simget & operator= (Simget const &o)
copy operator
virtual std::string name () const
return the name of the simget
mpi::communicator comm () const
po::variables_map const & vm () const
AboutData const & about () const
double meshSize () const
return the mesh size
double meshSizeInit () const
return the mesh size
int level () const
return the refinement level
ptree::ptree const & stats () const
return the statistics associated to the simget after calling run
ptree::ptree & stats ()
return the statistics associated to the simget after calling run
void setMeshSize (double h)
set the mesh size
void setMeshSizeInit (double h)
set the initial mesh size
void setLevel (int level)
set the refinment level if applicable
virtual void run (const double *X, unsigned long P, double *Y, unsigned long N)
void print (std::ostream &out, std::vector< ptree::ptree > &stats)
Additional Inherited Members
Protected Member Functions inherited from Feel::Simget
Simget & changeRepository (boost::format fmt)
Protected Attributes inherited from Feel::Simget
int M_level
double M_meshSize
double M_meshSizeInit
ptree::ptree M_stats
Member Function Documentation
void Feel::Stokes::run () virtual
run the convergence test
Implements Feel::Simget.
References Feel::boundaryfaces(), Feel::elements(), Feel::integrate(), Feel::Simget::meshSize(), and Feel::Simget::vm().
The documentation for this class was generated from the following file:
stokes.cpp