Feel++: ThreeFieldsLaplacian< Dim, Order1, Order2, Order3 > Class Template Reference
ThreeFieldsLaplacian< Dim, Order1, Order2, Order3 > Class Template Reference
Detailed Description
template<int Dim, int Order1, int Order2, int Order3>
class ThreeFieldsLaplacian< Dim, Order1, Order2, Order3 >
ThreeFieldsLaplacian Solver using continuous approximation spaces solve on and on
Template Parameters
Dim the geometric dimension of the problem (e.g. Dim=2 or 3)
Public Types
typedef boost::shared_ptr
< backend_type > backend_ptrtype
typedef Backend< value_type > backend_type
typedef bases< Lagrange
< Order1, Scalar > > basis1_type
typedef bases< Lagrange
< Order2, Scalar > > basis2_type
typedef Simplex< Dim, 1, Dim > convex_type
typedef space1_type::element_type element1_type
typedef space2_type::element_type element2_type
typedef boost::shared_ptr
< export_type > export_ptrtype
typedef Exporter< mesh_type > export_type
typedef bases< Lagrange
< Order3, Scalar > > interfaces_basis_type
typedef
interfaces_space_type::element_type interfaces_element_type
typedef boost::shared_ptr
< interfaces_space_type > interfaces_space_ptrtype
typedef FunctionSpace
< trace_mesh_type,
interfaces_basis_type > interfaces_space_type
typedef boost::shared_ptr
< mesh_type > mesh_ptrtype
typedef Mesh< convex_type > mesh_type
typedef FunctionSpace
< mesh_type, basis1_type > space1_type
typedef FunctionSpace
< mesh_type, basis2_type > space2_type
typedef
trace1_space_type::element_type trace1_element_type
typedef
space1_type::trace_functionspace_type trace1_space_type
typedef
trace2_space_type::element_type trace2_element_type
typedef
space2_type::trace_functionspace_type trace2_space_type
typedef boost::shared_ptr
< trace_export_type > trace_export_ptrtype
typedef Exporter< trace_mesh_type > trace_export_type
typedef
mesh_type::trace_mesh_ptrtype trace_mesh_ptrtype
typedef mesh_type::trace_mesh_type trace_mesh_type
typedef double value_type
Public Member Functions
mesh_ptrtype createMesh (double xmin, double xmax, double meshsize, int id)
trace_mesh_ptrtype createMesh (double meshSize, double interface)
void exportResults (element1_type &u, element2_type &v, trace1_element_type &t1, trace2_element_type &t2)
void run ()
ThreeFieldsLaplacian ()
Public Member Functions inherited from Feel::Simget
Simget ()
virtual ~Simget ()
destructor
Simget & operator= (Simget const &o)
copy operator
virtual std::string name () const
return the name of the simget
mpi::communicator comm () const
po::variables_map const & vm () const
AboutData const & about () const
double meshSize () const
return the mesh size
double meshSizeInit () const
return the mesh size
int level () const
return the refinement level
ptree::ptree const & stats () const
return the statistics associated to the simget after calling run
ptree::ptree & stats ()
return the statistics associated to the simget after calling run
void setMeshSize (double h)
set the mesh size
void setMeshSizeInit (double h)
set the initial mesh size
void setLevel (int level)
set the refinment level if applicable
virtual void run (const double *X, unsigned long P, double *Y, unsigned long N)
void print (std::ostream &out, std::vector< ptree::ptree > &stats)
Additional Inherited Members
Protected Member Functions inherited from Feel::Simget
Simget & changeRepository (boost::format fmt)
Protected Attributes inherited from Feel::Simget
int M_level
double M_meshSize
double M_meshSizeInit
ptree::ptree M_stats
Constructor & Destructor Documentation
template<int Dim, int Order1, int Order2, int Order3> ThreeFieldsLaplacian< Dim, Order1, Order2, Order3 >::ThreeFieldsLaplacian () inline
Constructor
Member Function Documentation
template<int Dim, int Order1, int Order2, int Order3> void ThreeFieldsLaplacian< Dim, Order1, Order2, Order3 >::run () virtual
simply execute the simget
Implements Feel::Simget.
References Feel::elements(), Feel::integrate(), and Feel::markedfaces().
The documentation for this class was generated from the following file:
threefields.cpp