Feel++: Feel::DAR< Dim > Class Template Reference
Feel::DAR< Dim > Class Template Reference
Detailed Description
template<int Dim>
class Feel::DAR< Dim >
DAR Solver using continuous approximation spaces solve on and on
Template Parameters
Dim the geometric dimension of the problem (e.g. Dim=1, 2 or 3)
Public Types
typedef bases< Lagrange< Order,
Scalar > > basis_type
the basis type of our approximation space
typedef Simplex< Dim > convex_type
geometry entities type composing the mesh, here Simplex in Dimension Dim of Order 1
typedef space_type::element_type element_type
an element type of the approximation function space
typedef boost::shared_ptr
< export_type > export_ptrtype
the exporter factory (shared_ptr<> type)
typedef Exporter< mesh_type > export_type
the exporter factory type
typedef boost::shared_ptr
< mesh_type > mesh_ptrtype
mesh shared_ptr<> type
typedef Mesh< convex_type > mesh_type
mesh type
typedef boost::shared_ptr
< space_type > space_ptrtype
the approximation function space type (shared_ptr<> type)
typedef FunctionSpace
< mesh_type, basis_type > space_type
the approximation function space type
typedef double value_type
numerical type is double
Public Member Functions
DAR ()
void run ()
Public Member Functions inherited from Feel::Simget
Simget ()
virtual ~Simget ()
destructor
Simget & operator= (Simget const &o)
copy operator
virtual std::string name () const
return the name of the simget
mpi::communicator comm () const
po::variables_map const & vm () const
AboutData const & about () const
double meshSize () const
return the mesh size
double meshSizeInit () const
return the mesh size
int level () const
return the refinement level
ptree::ptree const & stats () const
return the statistics associated to the simget after calling run
ptree::ptree & stats ()
return the statistics associated to the simget after calling run
void setMeshSize (double h)
set the mesh size
void setMeshSizeInit (double h)
set the initial mesh size
void setLevel (int level)
set the refinment level if applicable
virtual void run (const double *X, unsigned long P, double *Y, unsigned long N)
void print (std::ostream &out, std::vector< ptree::ptree > &stats)
Static Public Attributes
static const uint16_type Order = 2
Polynomial order .
Additional Inherited Members
Protected Member Functions inherited from Feel::Simget
Simget & changeRepository (boost::format fmt)
Protected Attributes inherited from Feel::Simget
int M_level
double M_meshSize
double M_meshSizeInit
ptree::ptree M_stats
Constructor & Destructor Documentation
template<int Dim> Feel::DAR< Dim >::DAR () inline
Constructor
Member Function Documentation
template<int Dim> void Feel::DAR< Dim >::run () virtual
simply execute the simget
The function space and some associated elements(functions) are then defined
 */
space_ptrtype Xh = space_type::New(mesh);
element_type u(Xh, "u");
element_type v(Xh, "v");
element_type gproj(Xh, "v");
define the expression of the exact solution and the expression of the right hand side such that is the exact solution
 */
//# marker1 #
auto g = sin(pi*Px())*cos(pi*Py())*cos(pi*Pz());
gproj = vf::project(Xh, elements(mesh), g);
auto grad_g = vec(+pi*cos(pi*Px())*cos(pi*Py())*cos(pi*Pz()),
                   -pi*sin( pi*Px() )*sin( pi*Py() )*cos( pi*Pz() ) );
auto beta = vec(cst(bx),cst(by));
auto f = (pi*pi*Dim*epsilon*g+trans(grad_g)*beta + mu*g);
//# endmarker1 #
Construction of the right hand side. F is the vector that holds the algebraic representation of the right habd side of the problem
 */
    //# marker2 #
    auto F = backend( _vm=this->vm() )->newVector( Xh );
    form1( _test=Xh, _vector=F, _init=true ) =
        integrate( _range=elements( mesh ), _expr=f*id( v ) );
    //# endmarker2 #
    if ( weak_dirichlet )
    {
        //# marker41 #
#if 1
        form1( _test=Xh, _vector=F ) +=
            integrate( _range=boundaryfaces( mesh ),
                       _expr=g*( -epsilon*grad( v )*vf::N()+penaldir*id( v )/hFace() ) );
#endif
        //# endmarker41 #
    }
create the matrix that will hold the algebraic representation of the left hand side
 */
size_type pattern=Pattern::COUPLED;
if (stab)
    pattern = Pattern::COUPLED|Pattern::EXTENDED;
auto D = backend()->newMatrix(_test=Xh, _trial=Xh, _pattern=pattern);
assemble $ u v$
 */
form2(_test=Xh, _trial=Xh, _matrix=D) =
    integrate( _range=elements( mesh ),
               _expr=( epsilon*gradt( u )*trans( grad( v ) )+( gradt( u )*beta )*id( v )+mu*idt( u )*id( v ) ) );
weak dirichlet conditions treatment for the boundaries marked 1 and 3
assemble
assemble
assemble
 */
        //# marker10 #
#if 1
        form2( _test=Xh, _trial=Xh, _matrix=D ) +=
            integrate( _range=boundaryfaces( mesh ),
                       _expr= ( -( epsilon*gradt( u )*vf::N() )*id( v )
                                -( epsilon*grad( v )*vf::N() )*idt( u )
                                +penaldir*id( v )*idt( u )/hFace() ) );
#else
        form2( _test=Xh, _trial=Xh, _matrix=D ) +=
            integrate( _range=boundaryfaces( mesh ),
                       _expr= ( -( epsilon*gradt( u )*vf::N() )*id( v ) ) );
#endif
        //# endmarker10 #
strong(algebraic) dirichlet conditions treatment for the boundaries marked 1 and 3
first close the matrix (the matrix must be closed first before any manipulation)
modify the matrix by cancelling out the rows and columns of D that are associated with the Dirichlet dof
 */
        //# marker5 #
#if 1
        form2( _test=Xh, _trial=Xh, _matrix=D ) +=
            on( _range=boundaryfaces( mesh ),_element=u, _rhs=F, _expr=g );
#endif
        //# endmarker5 #
solve the system
 */
//# marker6 #
backend(_rebuild=true,_vm=this->vm())->solve(_matrix=D, _solution=u, _rhs=F);
//# endmarker6 #
compute the
 */
//# marker7 #
LOG(INFO) << "||error||_L2=" << normL2(_range=elements(mesh), _expr=idv(u)-g) << "\n";
//# endmarker7 #
save the results
 */
element_type e(Xh, "e");
e = vf::project(Xh, elements(mesh), g);
export_ptrtype exporter(export_type::New(this->vm(),
                         ( boost::format( "%1%-%2%-%3%" )
                           % this->about().appName()
                           % shape
                           % Dim ).str() ) );
if (exporter->doExport())
{
    LOG(INFO) << "exportResults starts\n";
    exporter->step( 0 )->setMesh( mesh );
    exporter->step( 0 )->add( "u", u );
    exporter->step( 0 )->add( "g", e );
    exporter->save();
    LOG(INFO) << "exportResults done\n";
}
Implements Feel::Simget.
References Feel::boundaryfaces(), Feel::elements(), Feel::integrate(), Feel::internalfaces(), and Feel::project().
The documentation for this class was generated from the following file:
dar.cpp