Feel++: Feel::Exporter< MeshType, N > Class Template Reference
Feel::Exporter< MeshType, N > Class Template Reference abstract
#include <exporter.hpp>
Detailed Description
template<typename MeshType, int N = 1>
class Feel::Exporter< MeshType, N >
export Feel generated data to some file formats
Use the visitor and factory pattern.
Here is a snippet on how to use the Exporter class
#include <feel/feelfilters/exporter.hpp>
typedef Exporter<mesh_type> export_type;
typedef boost::shared_ptr<export_type> export_ptrtype;
// vm is a po::variables_map to get the command lines options
export_ptrtype exporter(export_type::New(vm);
// U is an element of a function space which we want to visualise
exporter->step(0)->setMesh(U.functionSpace()->mesh());
exporter->step(0)->add("u", U);
See Also
Laplacian
Author
Christophe Prud'homme
Public Types
Typedefs
typedef VisitorBase super1
typedef Visitor< MeshType > super2
typedef TimeSet< MeshType, N > timeset_type
typedef timeset_type::mesh_type mesh_type
typedef timeset_type::mesh_ptrtype mesh_ptrtype
typedef boost::shared_ptr
< timeset_type > timeset_ptrtype
typedef std::vector
< timeset_ptrtype > timeset_set_type
typedef timeset_set_type::iterator timeset_iterator
typedef
timeset_set_type::const_iterator timeset_const_iterator
typedef timeset_type::step_type step_type
typedef timeset_type::step_ptrtype step_ptrtype
Public Types inherited from Feel::Visitor< MeshType >
typedef void return_type
Public Member Functions
Accessors
bool doExport () const
std::string const & type () const
std::string const & prefix () const
int freq () const
int cptOfSave () const
file_type fileType () const
std::string path () const
Mutators
void setDoExport (bool do_export)
virtual Exporter< MeshType, N > * setOptions (std::string const &exp_prefix="")
virtual Exporter< MeshType, N > * setOptions (po::variables_map const &vm, std::string const &exp_prefix="") FEELPP_DEPRECATED
Exporter< MeshType, N > * setType (std::string const &__type)
Exporter< MeshType, N > * addPath (boost::format fmt)
void setPath (std::string path)
Exporter< MeshType, N > * setPrefix (std::string const &__prefix)
Exporter< MeshType, N > * setFreq (int __freq)
Exporter< MeshType, N > * setFileType (file_type __ft)
timeset_iterator beginTimeSet ()
timeset_iterator endTimeSet ()
timeset_const_iterator beginTimeSet () const
timeset_const_iterator endTimeSet () const
timeset_ptrtype defaultTimeSet ()
timeset_ptrtype timeSet (int ts)
bool useSingleTransientFile () const
void setUseSingleTransientFile (bool s)
void setMesh (mesh_ptrtype mesh, ExporterGeometry exgeo=EXPORTER_GEOMETRY_CHANGE_COORDS_ONLY)
template<typename F >
void add (std::string const &name, F const &u)
void addRegions ()
step_ptrtype step (double time)
step_ptrtype step (double time, int s)
Methods
void addTimeSet (timeset_ptrtype const &__ts)
virtual void save () const =0
void saveTimeSet () const
void restart (double __time)
void setWorldComm (WorldComm const &wc)
WorldComm const & worldComm () const
ExporterGeometry exporterGeometry () const
Public Member Functions inherited from Feel::Visitor< MeshType >
virtual ~Visitor ()
virtual base destructor
virtual return_type visit (MeshType *)=0
visit a data structure
return_type visit (MeshType &__t)
visit a data structure
Protected Attributes
int M_cptOfSave
bool M_do_export
ExporterGeometry M_ex_geometry
int M_freq
file_type M_ft
std::string M_path
std::string M_prefix
timeset_set_type M_ts_set
std::string M_type
bool M_use_single_transient_file
WorldComm M_worldComm
Constructors, destructor
Exporter (WorldComm const &worldComm=Environment::worldComm())
Exporter (std::string const &type, std::string const &prefix="", int freq=1, WorldComm const &worldComm=Environment::worldComm())
Exporter (po::variables_map const &vm, std::string const &exporter_prefix="", WorldComm const &worldComm=Environment::worldComm())
Exporter (Exporter const &exporter)
virtual ~Exporter ()
static boost::shared_ptr
< Exporter< MeshType, N > > New (std::string const &exportername, std::string prefix=Environment::about().appName(), WorldComm const &worldComm=Environment::worldComm())
static boost::shared_ptr
< Exporter< MeshType, N > > New (po::variables_map const &vm=Environment::vm(), std::string prefix=Environment::about().appName(), WorldComm const &worldComm=Environment::worldComm())
Constructor & Destructor Documentation
template<typename MeshType , int N> Feel::Exporter< MeshType, N >::Exporter (WorldComm const & worldComm = Environment::worldComm())
default constructor
References Feel::Exporter< MeshType, N >::doExport().
template<typename MeshType , int N> Feel::Exporter< MeshType, N >::Exporter (std::string const & type, std::string const & prefix = "", int freq = 1, WorldComm const & worldComm = Environment::worldComm())
Constructor
Parameters
type string containing the type of exporter (gmsh, ensight,...)
prefix the prefix for the file names of the exported data
freq an integer giving the frequency at which the data should be saved
template<typename MeshType , int N> Feel::Exporter< MeshType, N >::Exporter (po::variables_map const & vm, std::string const & exporter_prefix = "", WorldComm const & worldComm = Environment::worldComm())
Constructor
Parameters
vm variables_map containing the type of exporter and other exporter options
prefix the prefix for the file names of the exported data
freq an integer giving the frequency at which the data should be saved
References Feel::Exporter< MeshType, N >::doExport().
template<typename MeshType , int N> Feel::Exporter< MeshType, N >::Exporter (Exporter< MeshType, N > const & exporter)
copy constructor
template<typename MeshType , int N> Feel::Exporter< MeshType, N >::~Exporter () virtual
destructor
Member Function Documentation
template<typename MeshType , int N> Exporter< MeshType, N > * Feel::Exporter< MeshType, N >::addPath (boost::format fmt)
add an extra path to the current directory to save the data using the boost::format object fmt
template<typename MeshType, int N = 1> void Feel::Exporter< MeshType, N >::addTimeSet (timeset_ptrtype const & __ts) inline
add the timeset __ts to the Exporter
template<typename MeshType, int N = 1> int Feel::Exporter< MeshType, N >::cptOfSave () const inline
Returns
the frequency at which the results are saved
template<typename MeshType, int N = 1> bool Feel::Exporter< MeshType, N >::doExport () const inline
Returns
true if doing the export, false otherwise
template<typename MeshType, int N = 1> file_type Feel::Exporter< MeshType, N >::fileType () const inline
Returns
the file type format (ASCII or BINARY)
template<typename MeshType, int N = 1> int Feel::Exporter< MeshType, N >::freq () const inline
Returns
the frequency at which the results are saved
template<typename MeshType , int N> boost::shared_ptr< Exporter< MeshType, N > > Feel::Exporter< MeshType, N >::New (std::string const & exportername, std::string prefix = Environment::about().appName(), WorldComm const & worldComm = Environment::worldComm()) static
Static function instantiating from the Exporter Factory an exporter out of the exportername and using prefix for the prefix of the data files.
References Feel::Exporter< MeshType, N >::addTimeSet(), and Feel::Exporter< MeshType, N >::setPrefix().
template<typename MeshType , int N> boost::shared_ptr< Exporter< MeshType, N > > Feel::Exporter< MeshType, N >::New (po::variables_map const & vm = Environment::vm(), std::string prefix = Environment::about().appName(), WorldComm const & worldComm = Environment::worldComm()) static
Static function instantiating from the Exporter Factory an exporter out of the variables_map vm and using prefix for the prefix of the data files.
References Feel::ExporterEnsight< MeshType, N >::setOptions().
template<typename MeshType, int N = 1> std::string Feel::Exporter< MeshType, N >::path () const inline
Returns
the path to the saved files
template<typename MeshType, int N = 1> std::string const& Feel::Exporter< MeshType, N >::prefix () const inline
Returns
the prefix of the exported file names
template<typename MeshType, int N = 1> void Feel::Exporter< MeshType, N >::restart (double __time) inline
reload from file set of time which are been exported
template<typename MeshType, int N = 1> virtual void Feel::Exporter< MeshType, N >::save () const pure virtual
this p save function is defined by the Exporter subclasses and implement saving the data to files
Implemented in Feel::ExporterEnsight< MeshType, N >, Feel::ExporterEnsightGold< MeshType, N >, Feel::ExporterExodus< MeshType, N >, Feel::ExporterGnuplot< MeshType >, and Feel::ExporterGmsh< MeshType, N >.
template<typename MeshType, int N = 1> void Feel::Exporter< MeshType, N >::saveTimeSet () const inline
save in a file set of time which are been exported
template<typename MeshType, int N = 1> void Feel::Exporter< MeshType, N >::setDoExport (bool do_export) inline
set the doExport to do_export
template<typename MeshType, int N = 1> Exporter<MeshType,N>* Feel::Exporter< MeshType, N >::setFileType (file_type __ft) inline
set the file type to __ft (binary or ascii)
template<typename MeshType, int N = 1> Exporter<MeshType,N>* Feel::Exporter< MeshType, N >::setFreq (int __freq) inline
set the save frequency to __freq
template<typename MeshType , int N> Exporter< MeshType, N > * Feel::Exporter< MeshType, N >::setOptions (std::string const & exp_prefix = "") virtual
set the options from the variables_map vm as well as the prefix exp_prefix
Reimplemented in Feel::ExporterEnsight< MeshType, N >, Feel::ExporterEnsightGold< MeshType, N >, Feel::ExporterExodus< MeshType, N >, and Feel::ExporterGmsh< MeshType, N >.
template<typename MeshType, int N = 1> virtual Exporter<MeshType,N>* Feel::Exporter< MeshType, N >::setOptions (po::variables_map const & vm, std::string const & exp_prefix = "") inline virtual
set the options from the variables_map vm as well as the prefix exp_prefix
Reimplemented in Feel::ExporterEnsight< MeshType, N >, Feel::ExporterEnsightGold< MeshType, N >, Feel::ExporterExodus< MeshType, N >, Feel::ExporterGnuplot< MeshType >, and Feel::ExporterGmsh< MeshType, N >.
template<typename MeshType, int N = 1> void Feel::Exporter< MeshType, N >::setPath (std::string path) inline
set the path
template<typename MeshType, int N = 1> Exporter<MeshType,N>* Feel::Exporter< MeshType, N >::setPrefix (std::string const & __prefix) inline
set the prefix to __prefix
template<typename MeshType, int N = 1> Exporter<MeshType,N>* Feel::Exporter< MeshType, N >::setType (std::string const & __type) inline
set to __type the type of exporter (gmsh, ensight...)
template<typename MeshType, int N = 1> std::string const& Feel::Exporter< MeshType, N >::type () const inline
Returns
the type of exporter
The documentation for this class was generated from the following files:
exporter.hpp
exporterimpl.hpp