Feel++: Feel::GeoElement0D< Dim, SubFace, T > Class Template Reference
Feel::GeoElement0D< Dim, SubFace, T > Class Template Reference
Geometry Element classes
#include <geoelement.hpp>
Detailed Description
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double>
class Feel::GeoElement0D< Dim, SubFace, T >
Class for Points and Vertices
Public Types
typedef mpl::if_
< mpl::equal_to< mpl::int_
< SubFace::nDim >, mpl::int_
< 0 > >, mpl::identity
< self_type >, mpl::identity
< typename SubFace::template
Element< self_type >::type >
>::type::type element_type
typedef Geo0D< Dim, T > geo0d_type
typedef geo0d_type::node_type node_type
typedef self_type point_type
typedef GeoElement0D< Dim,
SubFace, T > self_type
typedef geo0d_type super
typedef SubFace super2
Public Types inherited from Feel::Geo0D< Dim, T >
typedef matrix_node
< value_type >::type matrix_node_type
typedef super2 node_type
typedef node< T, 2 >::type parametric_node_type
typedef Geo0D< Dim, T > self_type
typedef T value_type
Public Member Functions
GeoElement0D (size_type id, bool boundary=false)
Declares item id and if it is on boundary.
GeoElement0D (size_type id, node_type const &n, bool boundary=false)
GeoElement0D (size_type id, Real x, Real y, Real z, bool boundary=false)
template<typename SF >
GeoElement0D (GeoElement0D< Dim, SF, T > const &g)
size_type id () const
bool isGhostCell () const
bool isInterProcessDomain () const
bool isOnBoundary () const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker2 & marker2 ()
Marker3 const & marker3 () const
Marker3 & marker3 ()
MeshBase const * mesh () const
template<typename SF >
GeoElement0D & operator= (GeoElement0D< Dim, SF, T > const &g)
geo0d_type const & point (uint16_type) const
uint16_type processId () const
void setPoint (uint16_type, geo0d_type const &e)
Public Member Functions inherited from Feel::Geo0D< Dim, T >
matrix_node_type G () const
int gDim () const
template<uint16_type Dim>
Geo0D (uint16_type id, bool boundary)
template<uint16_type Dim>
Geo0D (uint16_type id, Real x, Real y, Real z, bool boundary)
Geo0D ()
Geo0D (size_type id, bool boundary=false, bool is_vertex=false)
Geo0D (size_type id, value_type x, value_type y, value_type z, bool boundary=false, bool is_vertex=false)
Geo0D (value_type x, value_type y, value_type z)
Geo0D (size_type id, node_type const &__x, bool boundary=false, bool is_vertex=false)
Geo0D (node_type const &__x)
template<typename AE >
Geo0D (ublas::vector_expression< AE > const &__expr)
Geo0D (Geo0D const &G)
int gTag () const
bool isParametric () const
bool isVertex () const
value_type measure () const
Geo0D const & node () const
value_type & operator() (int i)
value_type operator() (int i) const
template<typename AE >
Geo0D & operator+= (ublas::vector_expression< AE > const &expr)
bool operator< (Geo0D const &e) const
bool operator< (size_type __i) const
template<uint16_type Dim>
Geo0D< Dim > & operator= (Geo0D< Dim > const &G)
Geo0D & operator= (Geo0D const &G)
template<typename AE >
Geo0D & operator= (ublas::vector_expression< AE > const &expr)
bool operator== (Geo0D const &geo0d) const
parametric_node_type const & parametricCoordinates () const
void setAsVertex (bool v)
void setGDim (int gdim)
void setGTag (int gtag)
void setMarker (flag_type v)
void setMarker2 (flag_type v)
void setMarker3 (flag_type v)
void setMesh (MeshBase const *m)
void setNode (node_type const &__n)
void setParametricCoordinates (parametric_node_type const &x)
void setParametricCoordinates (value_type u, value_type v)
void setTags (std::vector< int > const &tags)
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
std::vector< int > tags () const
self_type & translate (node_type const &trans)
value_type u () const
value_type v () const
matrix_node_type vertices () const
Public Attributes
geo0d_type M_facept
Static Public Attributes
static const uint16_type nDim = 0
static const uint16_type nRealDim = Dim
static const uint16_type numLocalVertices = super::numVertices
Static Public Attributes inherited from Feel::Geo0D< Dim, T >
static const uint16_type nDim = Dim
Friends
class boost::serialization::access
Additional Inherited Members
Constructor & Destructor Documentation
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement0D< Dim, SubFace, T >::GeoElement0D (size_type id, Real x, Real y, Real z, bool boundary = false) inline
Declares item id and if it is on boundary, and provides coordinate data.
Member Function Documentation
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement0D< Dim, SubFace, T >::id () const inline
Returns
id
Reimplemented from Feel::GeoEntity< Simplex< 0, 1, Dim > >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement0D< Dim, SubFace, T >::isGhostCell () const inline
Returns
true if ghost cell, false otherwise
Reimplemented from Feel::GeoEntity< Simplex< 0, 1, Dim > >.
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::isGhostCell().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement0D< Dim, SubFace, T >::isInterProcessDomain () const inline
Returns
true if interprocess domain face, false otherwise
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::processId().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement0D< Dim, SubFace, T >::isOnBoundary () const inline
Returns
true if on the boundary, false otherwise
Reimplemented from Feel::GeoEntity< Simplex< 0, 1, Dim > >.
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::isOnBoundary().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker1 const& Feel::GeoElement0D< Dim, SubFace, T >::marker () const inline
Returns
marker1() index
Reimplemented from Feel::Geo0D< Dim, T >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker1& Feel::GeoElement0D< Dim, SubFace, T >::marker () inline
Returns
marker1() index
Reimplemented from Feel::Geo0D< Dim, T >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker2 const& Feel::GeoElement0D< Dim, SubFace, T >::marker2 () const inline
Returns
marker2() index
Reimplemented from Feel::Geo0D< Dim, T >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker2& Feel::GeoElement0D< Dim, SubFace, T >::marker2 () inline
Returns
marker2() index
Reimplemented from Feel::Geo0D< Dim, T >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker3 const& Feel::GeoElement0D< Dim, SubFace, T >::marker3 () const inline
Returns
marker3() index
Reimplemented from Feel::Geo0D< Dim, T >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker3& Feel::GeoElement0D< Dim, SubFace, T >::marker3 () inline
Returns
marker3() index
Reimplemented from Feel::Geo0D< Dim, T >.
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> MeshBase const* Feel::GeoElement0D< Dim, SubFace, T >::mesh () const inline
Returns
the mesh to which this geometric entity belongs to
Reimplemented from Feel::Geo0D< Dim, T >.
References Feel::Geo0D< Dim, T >::mesh().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> geo0d_type const& Feel::GeoElement0D< Dim, SubFace, T >::point (uint16_type) const inline
Returns
the point associated to the face
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement0D< Dim, SubFace, T >::processId () const inline
Returns
process id
Reimplemented from Feel::GeoEntity< Simplex< 0, 1, Dim > >.
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::processId().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> void Feel::GeoElement0D< Dim, SubFace, T >::setPoint (uint16_type , geo0d_type const & e) inline
set the geometrical point associated to the face
Reimplemented from Feel::Geo0D< Dim, T >.
The documentation for this class was generated from the following file:
geoelement.hpp