Feel++: Feel::ParameterSpace< P > Class Template Reference
Feel::ParameterSpace< P > Class Template Reference
#include <parameterspace.hpp>
Detailed Description
template<int P>
class Feel::ParameterSpace< P >
Parameter space class.
Author
Christophe Prud'homme
See Also
Classes
class Element
element of a parameter space
class Sampling
Parameter space sampling class.
Public Types
typedef boost::shared_ptr
< Element > element_ptrtype
typedef Element element_type
typedef boost::shared_ptr
< sampling_type > sampling_ptrtype
typedef Sampling sampling_type
Typedefs
typedef ParameterSpace< Dimension > parameterspace_type
typedef boost::shared_ptr
< parameterspace_type > parameterspace_ptrtype
Public Member Functions
bool check () const
element_type element ()
element_ptrtype elementPtr ()
sampling_ptrtype sampling ()
Operator overloads
ParameterSpace & operator= (ParameterSpace const &o)
copy operator
Accessors
int dimension () const
element_type const & min () const
element_type const & max () const
element_type logMiddle () const
the log-middle point of the parameter space
element_type middle () const
the middle point of the parameter space
Mutators
void setMin (element_type const &min)
void setMax (element_type const &max)
Static Public Member Functions
Methods
static element_type logRandom (parameterspace_ptrtype space, bool broadcast)
Returns a log random element of the parameter space.
static element_type logRandom1 (parameterspace_ptrtype space)
static element_type random (parameterspace_ptrtype space, bool broadcast=true)
Returns a log random element of the parameter space.
static std::vector< double > logEquidistributeInDirection (parameterspace_ptrtype space, int direction, int N)
Returns a vector representing the values of log equidistributed element of the parameter space in the given direction.
static element_type logEquidistributed (double factor, parameterspace_ptrtype space)
Returns a log equidistributed element of the parameter space.
static std::vector< double > equidistributeInDirection (parameterspace_ptrtype space, int direction, int N)
Returns a vector representing the values of equidistributed element of the parameter space in the given direction.
static element_type equidistributed (double factor, parameterspace_ptrtype space)
Returns a equidistributed element of the parameter space.
Static Public Attributes
Constants
static const uint16_type Dimension = P
dimension of the parameter space
Friends
class boost::serialization::access
Constructors, destructor
ParameterSpace ()
default constructor
ParameterSpace (ParameterSpace const &o)
copy constructor
ParameterSpace (element_type const &emin, element_type const &emax)
~ParameterSpace ()
destructor
static parameterspace_ptrtype New ()
Member Function Documentation
template<int P> int Feel::ParameterSpace< P >::dimension () const inline
Returns
the parameter space dimension
References Feel::ParameterSpace< P >::Dimension.
template<int P> static element_type Feel::ParameterSpace< P >::equidistributed (double factor, parameterspace_ptrtype space) inline static
Returns a equidistributed element of the parameter space.
Parameters
factor is a factor in [0,1]
template<int P> static std::vector<double> Feel::ParameterSpace< P >::equidistributeInDirection (parameterspace_ptrtype space, int direction, int N) inline static
Returns a vector representing the values of equidistributed element of the parameter space in the given direction.
Parameters
direction
N : number of samples in the direction
References Feel::ParameterSpace< P >::max(), and Feel::ParameterSpace< P >::min().
template<int P> static element_type Feel::ParameterSpace< P >::logEquidistributed (double factor, parameterspace_ptrtype space) inline static
Returns a log equidistributed element of the parameter space.
Parameters
factor is a factor in [0,1]
template<int P> static std::vector<double> Feel::ParameterSpace< P >::logEquidistributeInDirection (parameterspace_ptrtype space, int direction, int N) inline static
Returns a vector representing the values of log equidistributed element of the parameter space in the given direction.
Parameters
direction
N : number of samples in the direction
References Feel::ParameterSpace< P >::max(), and Feel::ParameterSpace< P >::min().
template<int P> element_type const& Feel::ParameterSpace< P >::max () const inline
return the maximum element
template<int P> element_type const& Feel::ParameterSpace< P >::min () const inline
return the minimum element
template<int P> static parameterspace_ptrtype Feel::ParameterSpace< P >::New () inline static
generate a shared_ptr out of a parameter space
template<int P> void Feel::ParameterSpace< P >::setMax (element_type const & max) inline
set the maximum element
References Feel::ParameterSpace< P >::max().
template<int P> void Feel::ParameterSpace< P >::setMin (element_type const & min) inline
set the minimum element
References Feel::ParameterSpace< P >::min().
The documentation for this class was generated from the following file:
parameterspace.hpp