Feel++: LShape< Dim > Class Template Reference
LShape< Dim > Class Template Reference
Detailed Description
template<int Dim>
class LShape< Dim >
LShape Solver using continuous approximation spaces solve on and on
Template Parameters
Dim the geometric dimension of the problem (e.g. Dim=1, 2 or 3)
Public Types
typedef bases< Lagrange< Order,
Scalar > > basis_type
the basis type of our approximation space
typedef Simplex< Dim > convex_type
geometry entities type composing the mesh, here Simplex in Dimension Dim of Order 1
typedef space_type::element_type element_type
an element type of the approximation function space
typedef boost::shared_ptr
< export_type > export_ptrtype
the exporter factory (shared_ptr<> type)
typedef Exporter< mesh_type > export_type
the exporter factory type
typedef boost::shared_ptr
< mesh_type > mesh_ptrtype
mesh shared_ptr<> type
typedef Mesh< convex_type > mesh_type
mesh type
typedef MeshAdaptation< Dim,
Order, GOrder > MeshAdapt
typedef bases< Lagrange
< 0, Scalar, Discontinuous > > p0_basis_type
Scalar P0 space.
typedef p0_space_type::element_type p0_element_type
typedef boost::shared_ptr
< p0_space_type > p0_space_ptrtype
typedef FunctionSpace
< mesh_type, p0_basis_type > p0_space_type
typedef bases< Lagrange
< 1, Vectorial > > p1vec_basis_type
Vectorial P1 space.
typedef boost::shared_ptr
< p1vec_space_type > p1vec_space_ptrtype
typedef FunctionSpace
< mesh_type, p1vec_basis_type > p1vec_space_type
typedef boost::shared_ptr
< space_type > space_ptrtype
the approximation function space type (shared_ptr<> type)
typedef FunctionSpace
< mesh_type, basis_type > space_type
the approximation function space type
typedef double value_type
numerical type is double
Public Member Functions
gmsh_ptrtype createLShapeGeo (double meshSize, double Lx, double Ly, double Lz)
LShape ()
void run ()
void run (const double *X, unsigned long P, double *Y, unsigned long N)
boost::tuple< double, double,
p0_element_type > zz_estimator (const element_type &U, const mesh_ptrtype &mesh)
Public Member Functions inherited from Feel::Simget
Simget ()
virtual ~Simget ()
destructor
Simget & operator= (Simget const &o)
copy operator
virtual std::string name () const
return the name of the simget
mpi::communicator comm () const
po::variables_map const & vm () const
AboutData const & about () const
double meshSize () const
return the mesh size
double meshSizeInit () const
return the mesh size
int level () const
return the refinement level
ptree::ptree const & stats () const
return the statistics associated to the simget after calling run
ptree::ptree & stats ()
return the statistics associated to the simget after calling run
void setMeshSize (double h)
set the mesh size
void setMeshSizeInit (double h)
set the initial mesh size
void setLevel (int level)
set the refinment level if applicable
void print (std::ostream &out, std::vector< ptree::ptree > &stats)
Static Public Attributes
static const uint16_type GOrder = 1
Geometrical order.
static const uint16_type Order = 2
Polynomial order .
Additional Inherited Members
Protected Member Functions inherited from Feel::Simget
Simget & changeRepository (boost::format fmt)
Protected Attributes inherited from Feel::Simget
int M_level
double M_meshSize
double M_meshSizeInit
ptree::ptree M_stats
Constructor & Destructor Documentation
template<int Dim> LShape< Dim >::LShape () inline
Constructor
Member Function Documentation
template<int Dim> void LShape< Dim >::run () virtual
simply execute the simget
Implements Feel::Simget.
template<int Dim> void LShape< Dim >::run (const double * X, unsigned long P, double * Y, unsigned long N) virtual
models the input/output relation
Set dimensions of Lshape geometry
Resolve - u = 1 on , with u = 0 on
Define right hand side :
Weak Dirichlet boundary conditions treatment :
Define left hand side
Weak Dirichlet boundary conditions treatment :
Solve the system
Exportation of results
Make a pause between two adaptations : testing purpose
update mesh_eps
Reimplemented from Feel::Simget.
References Feel::Backend< T >::build(), Feel::elements(), Feel::integrate(), and Feel::markedfaces().
The documentation for this class was generated from the following file:
Lshape.cpp