Feel++: Feel::CRBDB Class Reference
Feel::CRBDB Class Reference
#include <crbdb.hpp>
Detailed Description
brief description
Author
Christophe Prud'homme
See Also
Public Member Functions
Constructors, destructor
CRBDB ()
default constructor
CRBDB (std::string prefixdir, std::string name, std::string dbprefix, po::variables_map const &vm)
constructor from command line options
CRBDB (CRBDB const &)
copy constructor
virtual ~CRBDB ()
destructor
Operator overloads
CRBDB & operator= (CRBDB const &o)
copy operator
Accessors
std::string const & prefixDirectory () const
std::string const & name () const
std::string const & dbFilename () const
fs::path dbLocalPath () const
fs::path dbSystemPath () const
fs::path lookForDB () const
po::variables_map vm ()
po::variables_map vm () const
bool isDBLoaded () const
Mutators
void setDBFilename (std::string const &filename)
set the DB filename
Methods
virtual void saveDB ()
virtual bool loadDB ()
Protected Member Functions
template<class Archive >
void load (Archive &ar, const unsigned int version)
template<class Archive >
void save (Archive &ar, const unsigned int version) const
void setIsLoaded (bool isloaded)
Friends
class boost::serialization::access
Member Function Documentation
std::string const& Feel::CRBDB::dbFilename () const inline
Returns
the DB filename
fs::path Feel::CRBDB::dbLocalPath () const
Returns
the db local path
fs::path Feel::CRBDB::dbSystemPath () const
Returns
the db system path
References Feel::Info::prefix().
bool Feel::CRBDB::isDBLoaded () const inline
Returns
true if the DB has been loaded, false otherwise
bool Feel::CRBDB::loadDB () virtual
load the CRB database
Reimplemented in Feel::CRB< TruthModelType >, Feel::CRBSCM< TruthModelType >, Feel::CRBTrilinear< TruthModelType >, and Feel::EIM< ModelType >.
fs::path Feel::CRBDB::lookForDB () const
Returns
path to database, empty path if not found
References dbFilename(), dbLocalPath(), and dbSystemPath().
std::string const& Feel::CRBDB::name () const inline
Returns
name
std::string const& Feel::CRBDB::prefixDirectory () const inline
Returns
prefix directory
void Feel::CRBDB::saveDB () virtual
save the CRB database
Reimplemented in Feel::CRB< TruthModelType >, Feel::CRBSCM< TruthModelType >, Feel::CRBTrilinear< TruthModelType >, and Feel::EIM< ModelType >.
po::variables_map Feel::CRBDB::vm () inline
Returns
variables_map
po::variables_map Feel::CRBDB::vm () const inline
Returns
variables_map
The documentation for this class was generated from the following files:
crbdb.hpp
crbdb.cpp