Feel++: Feel::PeriodicLaplacian< Dim, Order > Class Template Reference
Feel::PeriodicLaplacian< Dim, Order > Class Template Reference
Detailed Description
template<int Dim, int Order>
class Feel::PeriodicLaplacian< Dim, Order >
Fat boundary method for the laplacian
Public Types
typedef boost::shared_ptr
< backend_type > backend_ptrtype
typedef Backend< value_type > backend_type
typedef bases< Lagrange< Order,
Scalar >, Lagrange< Order,
Scalar > > basis_composite_type
typedef bases< Lagrange< Order,
Scalar > > basis_type
typedef bases< Lagrange< Order,
Vectorial > > basis_vec_type
typedef
functionspace_type::element_type element_type
typedef Entity< Dim, 1, Dim > entity_type
typedef boost::shared_ptr
< export_type > export_ptrtype
typedef Exporter< mesh_type > export_type
typedef boost::shared_ptr
< functionspace_composite_type > functionspace_composite_ptrtype
typedef FunctionSpace
< mesh_type,
basis_composite_type,
Periodicity< Periodic
<>, NoPeriodicity > > functionspace_composite_type
typedef boost::shared_ptr
< functionspace_type > functionspace_ptrtype
typedef FunctionSpace
< mesh_type, basis_type,
Periodicity< Periodic<> > > functionspace_type
typedef boost::shared_ptr
< functionspace_vec_type > functionspace_vec_ptrtype
typedef FunctionSpace
< mesh_type, basis_vec_type,
Periodicity< Periodic<> > > functionspace_vec_type
typedef boost::shared_ptr
< mesh_type > mesh_ptrtype
typedef Mesh< entity_type > mesh_type
typedef double value_type
typedef
functionspace_vec_type::element_type vec_element_type
Public Member Functions
BOOST_MPL_ASSERT ((boost::is_base_and_derived< Feel::detail::periodicity_base, Periodicity< Periodic<> > >))
BOOST_MPL_ASSERT ((boost::is_base_and_derived< Feel::detail::periodic_base, Periodicity< Periodic<> > >))
BOOST_MPL_ASSERT ((boost::is_same< typename functionspace_type::periodicity_type, Periodicity< Periodic<> > >))
BOOST_MPL_ASSERT ((boost::is_same< mpl::bool_< functionspace_type::is_periodic >, mpl::bool_< true > >))
BOOST_MPL_ASSERT ((boost::is_same< mpl::bool_< functionspace_vec_type::is_periodic >, mpl::bool_< true > >))
BOOST_MPL_ASSERT ((boost::is_same< mpl::bool_< functionspace_composite_type::template sub_functionspace< 0 >::type::value_type::is_periodic >, mpl::bool_< true > >))
BOOST_MPL_ASSERT ((boost::is_same< mpl::bool_< functionspace_composite_type::template sub_functionspace< 1 >::type::value_type::is_periodic >, mpl::bool_< false > >))
PeriodicLaplacian ()
void run ()
Public Member Functions inherited from Feel::Simget
Simget ()
virtual ~Simget ()
destructor
Simget & operator= (Simget const &o)
copy operator
virtual std::string name () const
return the name of the simget
mpi::communicator comm () const
po::variables_map const & vm () const
AboutData const & about () const
double meshSize () const
return the mesh size
double meshSizeInit () const
return the mesh size
int level () const
return the refinement level
ptree::ptree const & stats () const
return the statistics associated to the simget after calling run
ptree::ptree & stats ()
return the statistics associated to the simget after calling run
void setMeshSize (double h)
set the mesh size
void setMeshSizeInit (double h)
set the initial mesh size
void setLevel (int level)
set the refinment level if applicable
virtual void run (const double *X, unsigned long P, double *Y, unsigned long N)
void print (std::ostream &out, std::vector< ptree::ptree > &stats)
Static Public Attributes
static const uint16_type imOrder = 2*Order
Additional Inherited Members
Protected Member Functions inherited from Feel::Simget
Simget & changeRepository (boost::format fmt)
Protected Attributes inherited from Feel::Simget
int M_level
double M_meshSize
double M_meshSizeInit
ptree::ptree M_stats
Constructor & Destructor Documentation
template<int Dim, int Order> Feel::PeriodicLaplacian< Dim, Order >::PeriodicLaplacian ()
constructor
References Feel::Simget::about(), Feel::boundaryfaces(), Feel::Simget::changeRepository(), Feel::markedfaces(), Feel::nelements(), and Feel::FunctionSpace< A0, A1, A2, A3, A4 >::New().
Member Function Documentation
template<int Dim, int Order> void Feel::PeriodicLaplacian< Dim, Order >::run () virtual
run the convergence test
Implements Feel::Simget.
References AUTO, Feel::elements(), Feel::integrate(), Feel::markedfaces(), and Feel::project().
The documentation for this class was generated from the following file:
periodic.cpp