Feel++: Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse Class Reference
Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse Class Reference
#include <geomap.hpp>
Detailed Description
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange>
class Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse
Inverse of the geometric mapping for a given context
Public Types
typedef boost::shared_ptr
< geometric_mapping_type > geometric_mapping_ptrtype
typedef GeoMap geometric_mapping_type
typedef
geometric_mapping_type::matrix_node_t_type matrix_node_t_type
typedef
geometric_mapping_type::matrix_node_t_type matrix_node_type
typedef
geometric_mapping_type::node_t_type node_t_type
typedef
geometric_mapping_type::node_t_type node_type
Public Member Functions
template<typename GeoElem >
Inverse (geometric_mapping_ptrtype __gm, GeoElem const &__ge, WorldComm const &worldComm=Environment::worldComm().subWorldCommSeq())
template<typename GeoElem >
Inverse (geometric_mapping_ptrtype __gm, GeoElem const &__ge, mpl::int_< 1 >, WorldComm const &worldComm=Environment::worldComm().subWorldCommSeq())
Accessors
geometric_mapping_ptrtype const & geometricMapping () const
uint16_type N () const
uint16_type P () const
node_t_type const & xRef () const
node_t_type const & xReal () const
matrix_type const & G () const
matrix_type const & K () const
value_type J () const
matrix_type const & B () const
node_type barycenterRef () const
node_type barycenterReal () const
bool isIn () const
bool isOnConvexSurface () const
Mutators
void setXReal (node_type const &__xreal)
matrix_node_t_type operator() (matrix_node_t_type const &real_pts, bool allow_extrapolation=false) const
Static Public Attributes
static const
fem::transformation_type trans = geometric_mapping_type::trans
Member Function Documentation
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> matrix_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::B () const inline
Returns
the pseudo-inverse of the gradient of the transformation at reference node
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> node_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::barycenterReal () const
Returns
the barycenter of the geometric nodes
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> node_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::barycenterRef () const inline
Returns
the barycenter of the reference nodes
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> matrix_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::G () const inline
Returns
the matrix associated with the geometric nodes
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> geometric_mapping_ptrtype const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::geometricMapping () const inline
Returns
the geometric mapping associated with the context
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::isIn () const inline
Returns
true if the node is in the convex defined by G, false otherwise
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::isOnConvexSurface () const inline
tell whether the point is on the surface of the convex
Returns
true if the point is on the surface, false otherwise
References Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::xReal(), and Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::xRef().
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> matrix_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::K () const inline
Returns
the gradient of the transformation at reference node
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::N () const inline
Returns
the dimension of the space of the real element
References Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::G().
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> void Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::setXReal (node_type const & __xreal) inline
set the real node
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> node_t_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::xReal () const inline
Returns
the node in the real element
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> node_t_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Inverse::xRef () const inline
Returns
the node in the reference element
The documentation for this class was generated from the following file:
geomap.hpp