Feel++: Convection Class Reference
Convection Class Reference
#include <convection.hpp>
Detailed Description
The class derives from the Application class the template arguments are :
Template Parameters
Order_s velocity polynomial order
Order_t temperature polynomial order
Order_p pressure polynomial order
Public Types
typedef boost::shared_ptr
< backend_type > backend_ptrtype
typedef Backend< double > backend_type
typedef Lagrange< Order_p,
Scalar, Continuous,
PointSetFekete > basis_p_type
typedef Lagrange< Order_t,
Scalar, Continuous,
PointSetFekete > basis_t_type
typedef bases< basis_u_type,
basis_p_type, basis_t_type > basis_type
typedef Lagrange< Order_s,
Vectorial, Continuous,
PointSetFekete > basis_u_type
typedef
element_type::sub_element
< 0 >::type element_0_type
typedef
element_type::sub_element
< 1 >::type element_1_type
typedef
element_type::sub_element
< 2 >::type element_2_type
typedef space_type::element_type element_type
typedef Simplex< CONVECTION_DIM > entity_type
typedef Exporter< mesh_type > export_type
typedef boost::shared_ptr
< funlin_type > funlin_ptrtype
typedef FsFunctionalLinear
< space_type > funlin_type
typedef boost::shared_ptr
< mesh_type > mesh_ptrtype
typedef Mesh< entity_type > mesh_type
typedef boost::shared_ptr
< oplin_type > oplin_ptrtype
typedef OperatorLinear
< space_type, space_type > oplin_type
typedef Convection self_type
typedef boost::shared_ptr
< space_type > space_ptrtype
typedef FunctionSpace
< mesh_type, basis_type > space_type
typedef
backend_type::sparse_matrix_ptrtype sparse_matrix_ptrtype
typedef FunctionSpace
< mesh_type, basis_t_type > t_space_type
typedef double value_type
numerical type is double
typedef
backend_type::vector_ptrtype vector_ptrtype
Public Types inherited from Feel::Application
typedef boost::ptr_list< Simget > simgets_type
Simget collection type.
typedef simgets_type::iterator simget_iterator
Simget iterator over the collection.
enum Stats {
FLAT = 1<<1,
HEADER = 1<<2,
ERRORS = 1<<3,
TIME = 1<<4,
DATA = 1<<5,
NUMBERS = 1<<6,
ALL = ERRORS | TIME | DATA | NUMBERS
}
Public Member Functions
Convection (int argc, char **argv, AboutData const &, po::options_description const &)
Feel::gmsh_ptrtype createMesh ()
void exportResults (boost::format, element_type &U, double t)
void exportResults (element_type &U, int i)
void run ()
void solve (sparse_matrix_ptrtype &D, element_type &u, vector_ptrtype &F)
void updateJacobian (const vector_ptrtype &X, sparse_matrix_ptrtype &J)
void updateResidual (const vector_ptrtype &X, vector_ptrtype &R)
Public Member Functions inherited from Feel::Application
Application ()
Application (AboutData const &ad)
Application (AboutData const &ad, po::options_description const &od)
Application (int argc, char **argv, AboutData const &ad)
Application (int argc, char **argv, AboutData const &ad, po::options_description const &od)
Application (Application const &app)
virtual ~Application ()
Application (int argc, char **argv, AboutData const &ad)
Application (int argc, char **argv, AboutData const &ad, po::options_description const &od)
~Application ()
Application (int argc, char **argv, AboutData const &ad)
Application (int argc, char **argv, AboutData const &ad, po::options_description const &od)
Application (Application const &)
~Application ()
void setName1 (std::string const &name1)
void setName2 (std::string const &name2)
void setH (double h, int precision=4)
void setDimension (int dim)
Application & changeRepository (boost::format)
WorldComm & comm ()
WorldComm const & comm () const
void barrier ()
void add (Simget *simget)
virtual void run (const double *X, unsigned long P, double *Y, unsigned long N)
void setStats (std::vector< std::string > const &keys)
void printStats (std::ostream &out, size_type stats=ALL) const
void printStats (std::ostream &out, std::vector< std::string > const &keys, size_type stats=ALL) const
std::string resultFileName () const
po::options_description const & optionsDescription () const
po::variables_map const & vm () const
AboutData const & about () const
int unknownArgc () const
char ** unknownArgv () const
uint16_type nProcess ()
uint16_type processId ()
bool isMPIInitialized () const
std::string rootRepository () const
simget_iterator begin ()
simget_iterator end ()
size_type nSimgets () const
bool verbose () const
bool isMPIInitialized () const
Static Public Attributes
static const int Order_p = CONVECTION_ORDER_P
static const int Order_s = CONVECTION_ORDER_U
static const int Order_t = CONVECTION_ORDER_T
Additional Inherited Members
Static Public Member Functions inherited from Feel::Application
static void barrier ()
static mpi::communicator const & comm ()
template<class T >
static void Send (const T &obj, int proc, int tag)
template<class T >
static void Broadcast (T &obj)
template<class T >
static void Recv (T &obj, int proc, int tag)
template<class T >
static void Broadcast (T &, int=0)
static void barrier ()
static bool initialized ()
static bool finalized ()
static std::string processorName ()
static bool initialized ()
static bool finalized ()
static std::string processorName ()
Protected Member Functions inherited from Feel::Application
void doOptions (int argc, char **argv)
void parseAndStoreOptions (po::command_line_parser parser, bool extra_parser=false)
void processGenericOptions ()
void setLogs ()
Member Function Documentation
void Convection::run () virtual
execute the set of Simget stored in the Application
Reimplemented from Feel::Application.
References Feel::Application::about(), Feel::boundaryfaces(), Feel::elements(), Feel::integrate(), Feel::markedfaces(), Feel::Exporter< MeshType, N >::New(), Feel::FunctionSpace< A0, A1, A2, A3, A4 >::New(), Feel::project(), and Feel::Application::vm().
The documentation for this class was generated from the following files:
convection.hpp
convection_jacobian.cpp
convection_jacobian1.cpp
convection_jacobian2.cpp
convection_lo.cpp
convection_lo2.cpp
convection_other.cpp
convection_residual.cpp
convection_run.cpp