Feel++: Geometry Element classes
Geometry Element classes
Detailed Description
Classes
class Feel::GeoElement0D< Dim, SubFace, T >
class Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >
class for 1D elements
class Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >
Class for 2D elements.
class Feel::GeoElement3D< Dim, GEOSHAPE, T >
Class for 3D elements.
Variables
static const uint16_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::nDim = super::nDim
static const uint16_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::nDim = super::nDim
static const uint16_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges = super::numEdges
Number of element edges.
static const uint16_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::numLocalVertices = super::numLocalVertices
Class Documentation
class Feel::GeoElement0D
Public Types
typedef mpl::if_
< mpl::equal_to< mpl::int_
< SubFace::nDim >, mpl::int_
< 0 > >, mpl::identity
< self_type >, mpl::identity
< typename SubFace::template
Element< self_type >::type >
>::type::type element_type
typedef Geo0D< Dim, T > geo0d_type
typedef super::matrix_node_type matrix_node_type
typedef geo0d_type::node_type node_type
typedef self_type point_type
typedef GeoElement0D< Dim,
SubFace, T > self_type
typedef geo0d_type super
typedef SubFace super2
Public Types inherited from Feel::Geo0D< Dim, T >
typedef matrix_node
< value_type >::type matrix_node_type
typedef super2 node_type
typedef node< T, 2 >::type parametric_node_type
typedef Geo0D< Dim, T > self_type
typedef T value_type
Public Types inherited from Feel::GeoEntity< Simplex< 0, 1, Dim > >
typedef Simplex< 0, 1, Dim > super
typedef GeoEntity< Simplex
< 0, 1, Dim > > GeoShape
typedef GeoEntity< Simplex
< 0, 1, Dim > > self_type
typedef
super::topological_face_type face_type
typedef face_type GeoBShape
typedef Simplex< 0, 1, Dim >
::edge_permutation_type edge_permutation_type
typedef Simplex< 0, 1, Dim >
::face_permutation_type face_permutation_type
typedef Simplex< 0, 1, Dim > convex_type
Public Member Functions
uint16_type boundaryEntityDimension () const
matrix_node_type G () const
GeoElement0D (size_type id, bool boundary=false)
Declares item id and if it is on boundary.
GeoElement0D (size_type id, node_type const &n, bool boundary=false)
GeoElement0D (size_type id, Real x, Real y, Real z, bool boundary=false)
template<typename SF >
GeoElement0D (GeoElement0D< Dim, SF, T > const &g)
size_type id () const
bool isGhostCell () const
bool isGhostFace () const
bool isInterProcessDomain () const
bool isOnBoundary () const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker2 & marker2 ()
Marker3 const & marker3 () const
Marker3 & marker3 ()
MeshBase const * mesh () const
template<typename SF >
GeoElement0D & operator= (GeoElement0D< Dim, SF, T > const &g)
size_type partition1 () const
size_type partition2 () const
geo0d_type const & point (uint16_type) const
uint16_type processId () const
void setPoint (uint16_type, geo0d_type const &e)
matrix_node_type vertices () const
Public Member Functions inherited from Feel::Geo0D< Dim, T >
matrix_node_type G () const
int gDim () const
template<uint16_type Dim>
Geo0D (uint16_type id, bool boundary)
template<uint16_type Dim>
Geo0D (uint16_type id, Real x, Real y, Real z, bool boundary)
Geo0D ()
Geo0D (size_type id, bool boundary=false, bool is_vertex=false)
Geo0D (size_type id, value_type x, value_type y, value_type z, bool boundary=false, bool is_vertex=false)
Geo0D (value_type x, value_type y, value_type z)
Geo0D (size_type id, node_type const &__x, bool boundary=false, bool is_vertex=false)
Geo0D (node_type const &__x)
template<typename AE >
Geo0D (ublas::vector_expression< AE > const &__expr)
Geo0D (Geo0D const &G)
int gTag () const
bool isParametric () const
bool isPeriodic () const
bool isVertex () const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker2 & marker2 ()
Marker3 const & marker3 () const
Marker3 & marker3 ()
size_type masterId () const
self_type const * masterVertex () const
value_type measure () const
MeshBase const * mesh () const
Geo0D const & node () const
value_type & operator() (int i)
value_type operator() (int i) const
template<typename AE >
Geo0D & operator+= (ublas::vector_expression< AE > const &expr)
bool operator< (Geo0D const &e) const
bool operator< (size_type __i) const
template<uint16_type Dim>
Geo0D< Dim > & operator= (Geo0D< Dim > const &G)
Geo0D & operator= (Geo0D const &G)
template<typename AE >
Geo0D & operator= (ublas::vector_expression< AE > const &expr)
bool operator== (Geo0D const &geo0d) const
parametric_node_type const & parametricCoordinates () const
void setAsVertex (bool v)
void setGDim (int gdim)
void setGTag (int gtag)
void setMarker (flag_type v)
void setMarker2 (flag_type v)
void setMarker3 (flag_type v)
void setMasterId (size_type id)
void setMasterVertex (self_type const *m)
void setMesh (MeshBase const *m)
void setNode (node_type const &__n)
void setParametricCoordinates (parametric_node_type const &x)
void setParametricCoordinates (value_type u, value_type v)
void setPoint (uint16_type const , self_type const &p)
void setTags (std::vector< int > const &tags)
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
std::vector< int > tags () const
self_type & translate (node_type const &trans)
value_type u () const
value_type v () const
matrix_node_type vertices () const
Public Member Functions inherited from Feel::GeoEntity< Simplex< 0, 1, Dim > >
GeoEntity ()
GeoEntity (size_type i, size_type geometry=Geometry, size_type shape=Shape, size_type context=MESH_ENTITY_INTERNAL)
GeoEntity (GeoEntity const &__me)
GeoEntity & operator= (GeoEntity const &__me)
virtual ~GeoEntity ()
bool operator== (GeoEntity const &e) const
bool operator< (GeoEntity const &e) const
bool operator< (size_type __i) const
size_type id () const
uint16_type refDim () const
uint16_type nPoints () const
uint16_type nVertices () const
uint16_type nEdges () const
uint16_type nFaces () const
constexpr uint16_type nTopologicalFaces () const
uint16_type nGeometricFaces () const
uint16_type nNormals () const
bool hasShape (size_type __shape) const
bool isAVolume () const
bool isASurface () const
bool isALine () const
bool isAPoint () const
bool isAPointShape () const
bool isALineShape () const
bool isATriangleShape () const
bool isAQuadrangleShape () const
bool isATetrahedraShape () const
bool isAHexahedraShape () const
bool isLinear () const
bool isBilinear () const
bool isQuadratic () const
bool isInternal () const
bool isOnBoundary () const
uint16_type boundaryEntityDimension () const
bool isGhostCell () const
uint16_type processId () const
void setProcessId (uint16_type pid)
uint16_type pidInPartition () const
void setProcessIdInPartition (uint16_type pid)
uint16_type partitionId () const
uint16_type numberOfPartitions () const
size_type numberOfNeighborPartitions () const
bool isLinkedToOtherPartitions () const
std::vector< int > const & neighborPartitionIds () const
std::vector< int > & neighborPartitionIds ()
void clearNeighborPartitionIds ()
void setIdInOthersPartitions (uint16_type pid, size_type id)
size_type idInOthersPartitions (uint16_type pid) const
std::map< uint16_type,
size_type > const & idInOthersPartitions () const
void clearIdInOthersPartitions ()
bool active () const
void setId (size_type id)
void setOnBoundary (bool b, uint16_type ent_d=invalid_uint16_type_value)
void setNumberOfPartitions (uint16_type np)
void setNumberOfNeighborPartitions (uint16_type nep)
void setNeighborPartitionIds (std::vector< int > const &npids)
void addNeighborPartitionId (int p)
self_type & addElement (size_type e)
size_type numberOfElements () const
std::set< size_type > const & elements () const
std::set< size_type > & elements ()
self_type & addElementGhost (int proc, size_type e)
size_type numberOfProcGhost () const
std::map< int, std::set
< size_type > > const & elementsGhost () const
void clearElementsGhost ()
Public Member Functions inherited from Feel::Simplex< 0, 1, Dim >
uint16_type dimension () const
uint16_type topologicalDimension () const
Public Member Functions inherited from Feel::Convex< Dim, Order, RDim >
Convex ()
default constructor
Convex (Convex const &)
copy constructor
virtual ~Convex ()
destructor
Convex & operator= (Convex const &o)
copy operator
Public Attributes
geo0d_type M_facept
Static Public Attributes
static const uint16_type nDim = 0
static const uint16_type nRealDim = Dim
static const uint16_type numLocalVertices = super::numVertices
Static Public Attributes inherited from Feel::Geo0D< Dim, T >
static const uint16_type nDim = Dim
Static Public Attributes inherited from Feel::GeoEntity< Simplex< 0, 1, Dim > >
static const size_type Shape
static const size_type Geometry
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const uint16_type numVertices
static const uint16_type numFaces
static const uint16_type numGeometricFaces
static const uint16_type numTopologicalFaces
static const uint16_type numEdges
static const uint16_type numNormals
static const uint16_type numPoints
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVolume
static const bool is_simplex
static const bool is_hypercube
Friends
class boost::serialization::access
Additional Inherited Members
Static Public Member Functions inherited from Feel::GeoEntity< Simplex< 0, 1, Dim > >
static uint16_type eToP (uint16_type const __localEdge, uint16_type const __point)
static uint16_type fToP (uint16_type const __localFace, uint16_type const __point)
static uint16_type fToE (uint16_type const __localFace, uint16_type const __edge)
Static Public Member Functions inherited from Feel::Simplex< 0, 1, Dim >
static uint16_type e2p (uint16_type e, uint16_type p)
static uint16_type f2e (uint16_type f, uint16_type e)
static uint16_type f2eLoc (uint16_type f, uint16_type e)
static uint16_type f2p (uint16_type f, uint16_type p)
static std::string name ()
static uint16_type nPointsOnEdge ()
static uint16_type nPointsOnFace ()
static uint16_type nPointsOnVertex ()
static uint16_type nPointsOnVolume ()
static uint32_type polyDims (int n)
static std::string type ()
Constructor & Destructor Documentation
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement0D< Dim, SubFace, T >::GeoElement0D (size_type id, Real x, Real y, Real z, bool boundary = false) inline
Declares item id and if it is on boundary, and provides coordinate data.
Member Function Documentation
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement0D< Dim, SubFace, T >::boundaryEntityDimension () const inline
Returns
maximum dimension of the sub-entity touching the boundary of the element
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement0D< Dim, SubFace, T >::id () const inline
Returns
id
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement0D< Dim, SubFace, T >::isGhostCell () const inline
Returns
true if ghost cell, false otherwise
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::isGhostCell().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement0D< Dim, SubFace, T >::isInterProcessDomain () const inline
Returns
true if interprocess domain face, false otherwise
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::processId().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement0D< Dim, SubFace, T >::isOnBoundary () const inline
Returns
true if on the boundary, false otherwise
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::isOnBoundary().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker1 const& Feel::GeoElement0D< Dim, SubFace, T >::marker () const inline
Returns
marker1() index
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker1& Feel::GeoElement0D< Dim, SubFace, T >::marker () inline
Returns
marker1() index
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker2 const& Feel::GeoElement0D< Dim, SubFace, T >::marker2 () const inline
Returns
marker2() index
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker2& Feel::GeoElement0D< Dim, SubFace, T >::marker2 () inline
Returns
marker2() index
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker3 const& Feel::GeoElement0D< Dim, SubFace, T >::marker3 () const inline
Returns
marker3() index
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> Marker3& Feel::GeoElement0D< Dim, SubFace, T >::marker3 () inline
Returns
marker3() index
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement0D< Dim, SubFace, T >::partition1 () const inline
Returns
process id
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::processId().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement0D< Dim, SubFace, T >::partition2 () const inline
Returns
process id
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::processId().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> geo0d_type const& Feel::GeoElement0D< Dim, SubFace, T >::point (uint16_type) const inline
Returns
the point associated to the face
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement0D< Dim, SubFace, T >::processId () const inline
Returns
process id
References Feel::GeoEntity< Simplex< 0, 1, Dim > >::processId().
template<uint16_type Dim, typename SubFace = SubFaceOfNone, typename T = double> void Feel::GeoElement0D< Dim, SubFace, T >::setPoint (uint16_type , geo0d_type const & e) inline
set the geometrical point associated to the face
class Feel::GeoElement1D
Public Types
typedef
super::edge_permutation_type edge_permutation_type
typedef self_type element_type
typedef ublas::bounded_array
< point_type
*, numLocalVertices >
::const_iterator face_const_iterator
typedef ublas::bounded_array
< point_type
*, numLocalVertices >
::iterator face_iterator
typedef
super::face_permutation_type face_permutation_type
typedef point_type GeoBElement
typedef GEOSHAPE GeoShape
typedef super::node_type node_type
typedef super::permutation_type permutation_type
typedef mpl::if_
< mpl::equal_to< mpl::int_
< nRealDim >, mpl::int_
< 1 > >, mpl::identity
< GeoElement0D< Dim, SubFaceOf
< self_type >, T >
>, mpl::identity
< GeoElement0D< Dim, SubFaceOf
< self_type >, T >
> >::type::type point_type
typedef GeoElement1D< Dim,
GEOSHAPE, SubFace, T > self_type
typedef GeoND< Dim, GEOSHAPE,
T, GeoElement0D< Dim,
SubFaceOfNone, T > > super
typedef SubFace super2
typedef
super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
typedef
super::edge_permutation_type edge_permutation_type
typedef self_type element_type
typedef
super::face_permutation_type face_permutation_type
typedef super::face_type face_type
typedef GEOSHAPE GeoShape
typedef GetGm< 1 >::ptrtype gm1_ptrtype
typedef GetGm< 1 >::type gm1_type
typedef GetGm< nOrder >::ptrtype gm_ptrtype
typedef GetGm< nOrder >::type gm_type
typedef matrix_node
< value_type >::type matrix_node_type
typedef node< value_type >::type node_type
typedef mpl::if_
< mpl::equal_to< mpl::int_
< nDim >, mpl::int_
< 1 > >, mpl::identity
< vertex_permutation_type >
, typename mpl::if_
< mpl::equal_to< mpl::int_
< nDim >, mpl::int_
< 2 > >, mpl::identity
< edge_permutation_type >
, mpl::identity
< face_permutation_type >
>::type >::type::type permutation_type
typedef ublas::bounded_array
< point_type *, numPoints >
::const_iterator point_const_iterator
typedef ublas::bounded_array
< point_type *, numPoints >
::iterator point_iterator
typedef PointType point_type
typedef GeoElement0D< Dim,
SubFaceOfNone, T > PointType
typedef
gm1_type::super::reference_convex_type reference_convex1_type
typedef
gm_type::super::reference_convex_type reference_convex_type
typedef GeoND< Dim, GEOSHAPE,
value_type, GeoElement0D< Dim,
SubFaceOfNone, T > > self_type
typedef T value_type
typedef
super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoEntity< GEOSHAPE >
typedef GEOSHAPE super
typedef GeoEntity< GEOSHAPE > GeoShape
typedef GeoEntity< GEOSHAPE > self_type
typedef
super::topological_face_type face_type
typedef face_type GeoBShape
typedef
GEOSHAPE::edge_permutation_type edge_permutation_type
typedef
GEOSHAPE::face_permutation_type face_permutation_type
typedef GEOSHAPE convex_type
Public Member Functions
BOOST_MPL_ASSERT_MSG ((condition), INVALID_ELEMENT_REAL_DIMENSION,(mpl::int_< Dim >, mpl::int_< nRealDim >, GEOSHAPE))
uint16_type boundaryEntityDimension () const
point_type const & edge (uint16_type i) const
point_type const & face (uint16_type i) const
vertex_permutation_type facePermutation (uint16_type i) const
point_type const * facePtr (uint16_type i) const
point_type * facePtr (uint16_type i)
std::pair< face_iterator,
face_iterator > faces ()
std::pair< face_const_iterator,
face_const_iterator > faces () const
GeoElement1D (size_type id=0)
GeoElement1D (GeoElement1D const &g)
size_type id () const
bool isGhostCell () const
bool isGhostFace () const
bool isInterProcessDomain () const
bool isOnBoundary () const
uint8_type map (uint8_type k_1) const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker3 const & marker3 () const
MeshBase const * mesh () const
GeoElement1D & operator= (GeoElement1D const &g)
size_type partition1 () const
size_type partition2 () const
edge_permutation_type permutation (uint16_type) const
uint16_type processId () const
void setFace (uint16_type const i, point_type const &p)
void setMap (uint8_type k_1, uint8_type k_2)
~GeoElement1D ()
Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
void applyDisplacement (int i, ublas::vector< double > const &u)
void applyDisplacementG (int i, ublas::vector< double > const &u)
node_type barycenter () const
point_iterator beginPoint ()
point_const_iterator beginPoint () const
point_iterator endPoint ()
point_const_iterator endPoint () const
void exchangePoints (const uint16_type otn[numPoints])
node_type faceBarycenter (uint16_type f) const
matrix_node_type faceBarycenters () const
double faceMeasure (uint16_type f) const
std::vector< double > const & faceMeasures () const
PointType const & facePoint (uint16_type __f, uint16_type const __i) const
uint16_type faceToOppositePoint (uint16_type const _localFace, uint16_type const _point) const
matrix_node_type const & G () const
matrix_node_type & G ()
GeoND ()
GeoND (size_type id)
GeoND (GeoND const &e)
gm_ptrtype gm () const
return the geometric mapping if a mesh was set
gm1_ptrtype gm1 () const
return the geometric mapping if a mesh was set
double h () const
bool hasPoints () const
double hEdge (uint16_type f) const
double hFace (uint16_type f) const
bool isAnticlockwiseOriented () const
bool isNeighbor (self_type const &G) const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker2 & marker2 ()
Marker3 const & marker3 () const
Marker3 & marker3 ()
double measure () const
value_type measurePointElementNeighbors () const
MeshBase const * mesh () const
std::pair< size_type,
size_type > const & neighbor (uint16_type n) const
uint16_type nNeighbors () const
uint16_type nOppositePointsPerFace () const
ublas::matrix_column
< matrix_node_type const > normal (uint16_type f) const
matrix_node_type const & normals () const
uint16_type nPoints () const
size_type numberOfPointElementNeighbors () const
permutation_type permutation (uint16_type) const
PointType & point (uint16_type i)
PointType const & point (uint16_type i) const
std::set< size_type > const & pointElementNeighborIds () const
PointType * pointPtr (uint16_type i)
PointType const * pointPtr (uint16_type i) const
PointType & reversepoint (uint16_type const i)
PointType const & reversepoint (uint16_type const i) const
void setMarker (flag_type v)
void setMarker2 (flag_type v)
void setMarker3 (flag_type v)
void setMeasurePointElementNeighbors (value_type meas)
set the measure of point element neighbors
void setMesh (MeshBase const *m) const
void setMeshAndGm (MeshBase const *m, gm_ptrtype const &gm, gm1_ptrtype const &gm1) const
void setNeighbor (uint16_type n, size_type neigh_id, size_type proc_id)
void setPoint (uint16_type const i, point_type const &p)
void setTags (std::vector< int > const &tags)
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
void swapPoints (const uint16_type &pt1, const uint16_type &pt2)
void update ()
void updateWithPc (typename gm_type::precompute_ptrtype const &pc, typename gm_type::faces_precompute_type &pcf)
matrix_node_type vertices () const
~GeoND ()
Public Member Functions inherited from Feel::GeoEntity< GEOSHAPE >
GeoEntity ()
GeoEntity (size_type i, size_type geometry=Geometry, size_type shape=Shape, size_type context=MESH_ENTITY_INTERNAL)
GeoEntity (GeoEntity const &__me)
GeoEntity & operator= (GeoEntity const &__me)
virtual ~GeoEntity ()
bool operator== (GeoEntity const &e) const
bool operator< (GeoEntity const &e) const
bool operator< (size_type __i) const
size_type id () const
uint16_type refDim () const
uint16_type nPoints () const
uint16_type nVertices () const
uint16_type nEdges () const
uint16_type nFaces () const
constexpr uint16_type nTopologicalFaces () const
uint16_type nGeometricFaces () const
uint16_type nNormals () const
bool hasShape (size_type __shape) const
bool isAVolume () const
bool isASurface () const
bool isALine () const
bool isAPoint () const
bool isAPointShape () const
bool isALineShape () const
bool isATriangleShape () const
bool isAQuadrangleShape () const
bool isATetrahedraShape () const
bool isAHexahedraShape () const
bool isLinear () const
bool isBilinear () const
bool isQuadratic () const
bool isInternal () const
bool isOnBoundary () const
uint16_type boundaryEntityDimension () const
bool isGhostCell () const
uint16_type processId () const
void setProcessId (uint16_type pid)
uint16_type pidInPartition () const
void setProcessIdInPartition (uint16_type pid)
uint16_type partitionId () const
uint16_type numberOfPartitions () const
size_type numberOfNeighborPartitions () const
bool isLinkedToOtherPartitions () const
std::vector< int > const & neighborPartitionIds () const
std::vector< int > & neighborPartitionIds ()
void clearNeighborPartitionIds ()
void setIdInOthersPartitions (uint16_type pid, size_type id)
size_type idInOthersPartitions (uint16_type pid) const
std::map< uint16_type,
size_type > const & idInOthersPartitions () const
void clearIdInOthersPartitions ()
bool active () const
void setId (size_type id)
void setOnBoundary (bool b, uint16_type ent_d=invalid_uint16_type_value)
void setNumberOfPartitions (uint16_type np)
void setNumberOfNeighborPartitions (uint16_type nep)
void setNeighborPartitionIds (std::vector< int > const &npids)
void addNeighborPartitionId (int p)
self_type & addElement (size_type e)
size_type numberOfElements () const
std::set< size_type > const & elements () const
std::set< size_type > & elements ()
self_type & addElementGhost (int proc, size_type e)
size_type numberOfProcGhost () const
std::map< int, std::set
< size_type > > const & elementsGhost () const
void clearElementsGhost ()
Static Public Attributes
static const bool condition = (Dim==nRealDim)
static const uint16_type nDim = super::nDim
static const uint16_type nOrder = super::nOrder
static const uint16_type nRealDim = super::nRealDim
static const uint16_type numLocalEdges = super::numEdges
static const uint16_type numLocalFaces = super::numLocalVertices
static const uint16_type numLocalVertices = super::numLocalVertices
Static Public Attributes inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const int numEdges
static const int numFaces
static const uint16_type numLocalEdges
static const uint16_type numLocalPoints
static const uint16_type numLocalVertices
static const uint16_type numNeighbors
static const uint16_type numPoints
static const int numTopologicalFaces
static const uint16_type numVertices
static const size_type Shape
Static Public Attributes inherited from Feel::GeoEntity< GEOSHAPE >
static const size_type Shape
static const size_type Geometry
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const uint16_type numVertices
static const uint16_type numFaces
static const uint16_type numGeometricFaces
static const uint16_type numTopologicalFaces
static const uint16_type numEdges
static const uint16_type numNormals
static const uint16_type numPoints
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVolume
static const bool is_simplex
static const bool is_hypercube
Friends
class boost::serialization::access
Additional Inherited Members
Static Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
static uint16_type fToP (uint16_type const _localFace, uint16_type const _point)
Constructor & Destructor Documentation
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::GeoElement1D (size_type id = 0) inline explicit
default constructor, make it explicit to avoid implict inversion to size_type
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::GeoElement1D (GeoElement1D< Dim, GEOSHAPE, SubFace, T > const & g) inline
copy consttructor
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::~GeoElement1D () inline
destructor
Member Function Documentation
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::boundaryEntityDimension () const inline
Returns
maximum dimension of the sub-entity touching the boundary of the element
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> vertex_permutation_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::facePermutation (uint16_type i) const inline
See Also
edgePermutation(), permutation()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> std::pair<face_iterator,face_iterator> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::faces () inline
Returns
the iterator pair (begin,end) of faces
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> std::pair<face_const_iterator,face_const_iterator> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::faces () const inline
Returns
the iterator pair (begin,end) of faces
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::id () const inline
Returns
true if on the boundary, false otherwise
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::isGhostCell () const inline
Returns
true if ghost cell, false otherwise
References Feel::GeoEntity< GEOSHAPE >::isGhostCell().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::isInterProcessDomain () const inline
Returns
true if interprocess domain face, false otherwise
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::isOnBoundary () const inline
Returns
true if on the boundary, false otherwise
References Feel::GeoEntity< GEOSHAPE >::isOnBoundary().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> GeoElement1D& Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::operator= (GeoElement1D< Dim, GEOSHAPE, SubFace, T > const & g) inline
copy operator
References Feel::operator=().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::partition1 () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::partition2 () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::processId () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> void Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T >::setFace (uint16_type const i, point_type const & p) inline
Inserts a point as face of the edge geometric element
class Feel::GeoElement2D
Public Types
typedef
super::edge_permutation_type edge_permutation_type
typedef mpl::if_
< mpl::equal_to< mpl::int_
< nRealDim >, mpl::int_
< 2 > >, mpl::identity
< GeoElement1D< Dim,
entity_face_type, SubFaceOf
< self_type >, T >
>, mpl::identity
< GeoElement1D< Dim,
entity_face_type, SubFaceOf
< self_type >, T >
> >::type::type edge_type
typedef
super2::element_connectivity_type element_connectivity_type
typedef self_type element_type
typedef super::face_type entity_face_type
typedef std::vector< edge_type * >
::const_iterator face_const_iterator
typedef std::vector< edge_type * >
::iterator face_iterator
typedef
super::face_permutation_type face_permutation_type
typedef GEOSHAPE GeoShape
typedef super::node_type node_type
typedef
super::edge_permutation_type permutation_type
typedef GeoElement0D< Dim,
SubFaceOfNone, T > point_type
typedef GeoElement2D< Dim,
GEOSHAPE, SubFace, T > self_type
typedef GeoND< Dim, GEOSHAPE,
T, GeoElement0D< Dim,
SubFaceOfNone, T > > super
typedef SubFace super2
typedef
super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
typedef
super::edge_permutation_type edge_permutation_type
typedef self_type element_type
typedef
super::face_permutation_type face_permutation_type
typedef super::face_type face_type
typedef GEOSHAPE GeoShape
typedef GetGm< 1 >::ptrtype gm1_ptrtype
typedef GetGm< 1 >::type gm1_type
typedef GetGm< nOrder >::ptrtype gm_ptrtype
typedef GetGm< nOrder >::type gm_type
typedef matrix_node
< value_type >::type matrix_node_type
typedef node< value_type >::type node_type
typedef mpl::if_
< mpl::equal_to< mpl::int_
< nDim >, mpl::int_
< 1 > >, mpl::identity
< vertex_permutation_type >
, typename mpl::if_
< mpl::equal_to< mpl::int_
< nDim >, mpl::int_
< 2 > >, mpl::identity
< edge_permutation_type >
, mpl::identity
< face_permutation_type >
>::type >::type::type permutation_type
typedef ublas::bounded_array
< point_type *, numPoints >
::const_iterator point_const_iterator
typedef ublas::bounded_array
< point_type *, numPoints >
::iterator point_iterator
typedef PointType point_type
typedef GeoElement0D< Dim,
SubFaceOfNone, T > PointType
typedef
gm1_type::super::reference_convex_type reference_convex1_type
typedef
gm_type::super::reference_convex_type reference_convex_type
typedef GeoND< Dim, GEOSHAPE,
value_type, GeoElement0D< Dim,
SubFaceOfNone, T > > self_type
typedef T value_type
typedef
super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoEntity< GEOSHAPE >
typedef GEOSHAPE super
typedef GeoEntity< GEOSHAPE > GeoShape
typedef GeoEntity< GEOSHAPE > self_type
typedef
super::topological_face_type face_type
typedef face_type GeoBShape
typedef
GEOSHAPE::edge_permutation_type edge_permutation_type
typedef
GEOSHAPE::face_permutation_type face_permutation_type
typedef GEOSHAPE convex_type
Public Member Functions
BOOST_MPL_ASSERT_MSG ((condition), INVALID_ELEMENT_REAL_DIMENSION,(mpl::int_< Dim >, mpl::int_< nRealDim >, GEOSHAPE))
uint16_type boundaryEntityDimension () const
void disconnectSubEntities ()
edge_type const & edge (uint16_type i) const
edge_type & edge (uint16_type i)
edge_permutation_type edgePermutation (uint16_type i) const
edge_type & face (uint16_type i)
edge_type const & face (uint16_type i) const
edge_permutation_type facePermutation (uint16_type i) const
edge_type const * facePtr (uint16_type i) const
std::pair< face_iterator,
face_iterator > faces ()
std::pair< face_const_iterator,
face_const_iterator > faces () const
GeoElement2D (size_type id=0)
GeoElement2D (GeoElement2D const &g)
size_type id () const
bool isGhostCell () const
bool isGhostFace () const
bool isInterProcessDomain () const
bool isOnBoundary () const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker3 const & marker3 () const
MeshBase const * mesh () const
GeoElement2D & operator= (GeoElement2D const &g)
size_type partition1 () const
size_type partition2 () const
edge_permutation_type permutation (uint16_type i) const
uint16_type processId () const
void setEdge (uint16_type i, edge_type const &p)
void setEdgePermutation (uint16_type i, edge_permutation_type o)
void setFace (uint16_type const i, edge_type const &p)
~GeoElement2D ()
Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
void applyDisplacement (int i, ublas::vector< double > const &u)
void applyDisplacementG (int i, ublas::vector< double > const &u)
node_type barycenter () const
point_iterator beginPoint ()
point_const_iterator beginPoint () const
point_iterator endPoint ()
point_const_iterator endPoint () const
void exchangePoints (const uint16_type otn[numPoints])
node_type faceBarycenter (uint16_type f) const
matrix_node_type faceBarycenters () const
double faceMeasure (uint16_type f) const
std::vector< double > const & faceMeasures () const
PointType const & facePoint (uint16_type __f, uint16_type const __i) const
uint16_type faceToOppositePoint (uint16_type const _localFace, uint16_type const _point) const
matrix_node_type const & G () const
matrix_node_type & G ()
GeoND ()
GeoND (size_type id)
GeoND (GeoND const &e)
gm_ptrtype gm () const
return the geometric mapping if a mesh was set
gm1_ptrtype gm1 () const
return the geometric mapping if a mesh was set
double h () const
bool hasPoints () const
double hEdge (uint16_type f) const
double hFace (uint16_type f) const
bool isAnticlockwiseOriented () const
bool isNeighbor (self_type const &G) const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker2 & marker2 ()
Marker3 const & marker3 () const
Marker3 & marker3 ()
double measure () const
value_type measurePointElementNeighbors () const
MeshBase const * mesh () const
std::pair< size_type,
size_type > const & neighbor (uint16_type n) const
uint16_type nNeighbors () const
uint16_type nOppositePointsPerFace () const
ublas::matrix_column
< matrix_node_type const > normal (uint16_type f) const
matrix_node_type const & normals () const
uint16_type nPoints () const
size_type numberOfPointElementNeighbors () const
permutation_type permutation (uint16_type) const
PointType & point (uint16_type i)
PointType const & point (uint16_type i) const
std::set< size_type > const & pointElementNeighborIds () const
PointType * pointPtr (uint16_type i)
PointType const * pointPtr (uint16_type i) const
PointType & reversepoint (uint16_type const i)
PointType const & reversepoint (uint16_type const i) const
void setMarker (flag_type v)
void setMarker2 (flag_type v)
void setMarker3 (flag_type v)
void setMeasurePointElementNeighbors (value_type meas)
set the measure of point element neighbors
void setMesh (MeshBase const *m) const
void setMeshAndGm (MeshBase const *m, gm_ptrtype const &gm, gm1_ptrtype const &gm1) const
void setNeighbor (uint16_type n, size_type neigh_id, size_type proc_id)
void setPoint (uint16_type const i, point_type const &p)
void setTags (std::vector< int > const &tags)
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
void swapPoints (const uint16_type &pt1, const uint16_type &pt2)
void update ()
void updateWithPc (typename gm_type::precompute_ptrtype const &pc, typename gm_type::faces_precompute_type &pcf)
matrix_node_type vertices () const
~GeoND ()
Public Member Functions inherited from Feel::GeoEntity< GEOSHAPE >
GeoEntity ()
GeoEntity (size_type i, size_type geometry=Geometry, size_type shape=Shape, size_type context=MESH_ENTITY_INTERNAL)
GeoEntity (GeoEntity const &__me)
GeoEntity & operator= (GeoEntity const &__me)
virtual ~GeoEntity ()
bool operator== (GeoEntity const &e) const
bool operator< (GeoEntity const &e) const
bool operator< (size_type __i) const
size_type id () const
uint16_type refDim () const
uint16_type nPoints () const
uint16_type nVertices () const
uint16_type nEdges () const
uint16_type nFaces () const
constexpr uint16_type nTopologicalFaces () const
uint16_type nGeometricFaces () const
uint16_type nNormals () const
bool hasShape (size_type __shape) const
bool isAVolume () const
bool isASurface () const
bool isALine () const
bool isAPoint () const
bool isAPointShape () const
bool isALineShape () const
bool isATriangleShape () const
bool isAQuadrangleShape () const
bool isATetrahedraShape () const
bool isAHexahedraShape () const
bool isLinear () const
bool isBilinear () const
bool isQuadratic () const
bool isInternal () const
bool isOnBoundary () const
uint16_type boundaryEntityDimension () const
bool isGhostCell () const
uint16_type processId () const
void setProcessId (uint16_type pid)
uint16_type pidInPartition () const
void setProcessIdInPartition (uint16_type pid)
uint16_type partitionId () const
uint16_type numberOfPartitions () const
size_type numberOfNeighborPartitions () const
bool isLinkedToOtherPartitions () const
std::vector< int > const & neighborPartitionIds () const
std::vector< int > & neighborPartitionIds ()
void clearNeighborPartitionIds ()
void setIdInOthersPartitions (uint16_type pid, size_type id)
size_type idInOthersPartitions (uint16_type pid) const
std::map< uint16_type,
size_type > const & idInOthersPartitions () const
void clearIdInOthersPartitions ()
bool active () const
void setId (size_type id)
void setOnBoundary (bool b, uint16_type ent_d=invalid_uint16_type_value)
void setNumberOfPartitions (uint16_type np)
void setNumberOfNeighborPartitions (uint16_type nep)
void setNeighborPartitionIds (std::vector< int > const &npids)
void addNeighborPartitionId (int p)
self_type & addElement (size_type e)
size_type numberOfElements () const
std::set< size_type > const & elements () const
std::set< size_type > & elements ()
self_type & addElementGhost (int proc, size_type e)
size_type numberOfProcGhost () const
std::map< int, std::set
< size_type > > const & elementsGhost () const
void clearElementsGhost ()
Static Public Attributes
static const bool condition = (Dim==nRealDim)
static const uint16_type nDim = super::nDim
static const uint16_type nOrder = super::nOrder
static const uint16_type nRealDim = super::nRealDim
static const uint16_type numLocalEdges = super::numEdges
Number of element edges.
static const uint16_type numLocalFaces = super::numFaces
Static Public Attributes inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const int numEdges
static const int numFaces
static const uint16_type numLocalEdges
static const uint16_type numLocalPoints
static const uint16_type numLocalVertices
static const uint16_type numNeighbors
static const uint16_type numPoints
static const int numTopologicalFaces
static const uint16_type numVertices
static const size_type Shape
Static Public Attributes inherited from Feel::GeoEntity< GEOSHAPE >
static const size_type Shape
static const size_type Geometry
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const uint16_type numVertices
static const uint16_type numFaces
static const uint16_type numGeometricFaces
static const uint16_type numTopologicalFaces
static const uint16_type numEdges
static const uint16_type numNormals
static const uint16_type numPoints
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVolume
static const bool is_simplex
static const bool is_hypercube
Friends
class boost::serialization::access
Additional Inherited Members
Static Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
static uint16_type fToP (uint16_type const _localFace, uint16_type const _point)
Constructor & Destructor Documentation
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::GeoElement2D (size_type id = 0) inline explicit
default constructor, make it explicit to avoid implict inversion to size_type
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::GeoElement2D (GeoElement2D< Dim, GEOSHAPE, SubFace, T > const & g) inline
copy consttructor
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::~GeoElement2D () inline
destructor
Member Function Documentation
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::boundaryEntityDimension () const inline
Returns
maximum dimension of the sub-entity touching the boundary of the element
References Feel::GeoEntity< GEOSHAPE >::boundaryEntityDimension().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> edge_type const& Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::edge (uint16_type i) const inline
See Also
face()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::id(), and Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> edge_type& Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::edge (uint16_type i) inline
See Also
face()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::id(), and Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> edge_permutation_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::edgePermutation (uint16_type i) const inline
See Also
facePermutation(), permutation()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> edge_type const& Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::face (uint16_type i) const inline
See Also
edge()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::id(), and Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> edge_permutation_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::facePermutation (uint16_type i) const inline
See Also
edgePermutation(), permutation()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> std::pair<face_iterator,face_iterator> Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::faces () inline
Returns
the iterator pair (begin,end) of faces
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> std::pair<face_const_iterator,face_const_iterator> Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::faces () const inline
Returns
the iterator pair (begin,end) of faces
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::id () const inline
Returns
true if on the boundary, false otherwise
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::isGhostCell () const inline
Returns
true if ghost cell, false otherwise
References Feel::GeoEntity< GEOSHAPE >::isGhostCell().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::isInterProcessDomain () const inline
Returns
true if interprocess domain face, false otherwise
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> bool Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::isOnBoundary () const inline
Returns
true if on the boundary, false otherwise
References Feel::GeoEntity< GEOSHAPE >::isOnBoundary().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> GeoElement2D& Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::operator= (GeoElement2D< Dim, GEOSHAPE, SubFace, T > const & g) inline
copy operator
References Feel::operator=().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::partition1 () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> size_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::partition2 () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> edge_permutation_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::permutation (uint16_type i) const inline
See Also
edgePermutation(), facePermutation()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::id(), and Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> uint16_type Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::processId () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> void Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::setEdge (uint16_type i, edge_type const & p) inline
Inserts a point. Uses point references put point
See Also
setFace()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone, typename T = double> void Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::setFace (uint16_type const i, edge_type const & p) inline
Inserts an edge.
See Also
setEdge()
References Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T >::numLocalEdges.
class Feel::GeoElement3D
Public Types
typedef
super::edge_permutation_type edge_permutation_type
typedef GeoElement1D< Dim,
typename
entity_face_type::topological_face_type,
SubFaceOf< face_type >, T > edge_type
typedef self_type element_type
typedef super::face_type entity_face_type
typedef ublas::bounded_array
< face_type *, numLocalFaces >
::const_iterator face_const_iterator
typedef ublas::bounded_array
< face_type *, numLocalFaces >
::iterator face_iterator
typedef
super::face_permutation_type face_permutation_type
typedef GeoElement2D< Dim,
entity_face_type, SubFaceOf
< self_type >, T > face_type
typedef GEOSHAPE GeoShape
typedef super::node_type node_type
typedef
super::face_permutation_type permutation_type
typedef GeoElement0D< Dim,
SubFaceOfNone, T > point_type
typedef GeoElement3D< Dim,
GEOSHAPE, T > self_type
typedef GeoND< Dim, GEOSHAPE,
T, GeoElement0D< Dim,
SubFaceOfNone, T > > super
typedef SubFaceOfNone super2
typedef
super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
typedef
super::edge_permutation_type edge_permutation_type
typedef self_type element_type
typedef
super::face_permutation_type face_permutation_type
typedef super::face_type face_type
typedef GEOSHAPE GeoShape
typedef GetGm< 1 >::ptrtype gm1_ptrtype
typedef GetGm< 1 >::type gm1_type
typedef GetGm< nOrder >::ptrtype gm_ptrtype
typedef GetGm< nOrder >::type gm_type
typedef matrix_node
< value_type >::type matrix_node_type
typedef node< value_type >::type node_type
typedef mpl::if_
< mpl::equal_to< mpl::int_
< nDim >, mpl::int_
< 1 > >, mpl::identity
< vertex_permutation_type >
, typename mpl::if_
< mpl::equal_to< mpl::int_
< nDim >, mpl::int_
< 2 > >, mpl::identity
< edge_permutation_type >
, mpl::identity
< face_permutation_type >
>::type >::type::type permutation_type
typedef ublas::bounded_array
< point_type *, numPoints >
::const_iterator point_const_iterator
typedef ublas::bounded_array
< point_type *, numPoints >
::iterator point_iterator
typedef PointType point_type
typedef GeoElement0D< Dim,
SubFaceOfNone, T > PointType
typedef
gm1_type::super::reference_convex_type reference_convex1_type
typedef
gm_type::super::reference_convex_type reference_convex_type
typedef GeoND< Dim, GEOSHAPE,
value_type, GeoElement0D< Dim,
SubFaceOfNone, T > > self_type
typedef T value_type
typedef
super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoEntity< GEOSHAPE >
typedef GEOSHAPE super
typedef GeoEntity< GEOSHAPE > GeoShape
typedef GeoEntity< GEOSHAPE > self_type
typedef
super::topological_face_type face_type
typedef face_type GeoBShape
typedef
GEOSHAPE::edge_permutation_type edge_permutation_type
typedef
GEOSHAPE::face_permutation_type face_permutation_type
typedef GEOSHAPE convex_type
Public Types inherited from Feel::SubFaceOfNone
typedef boost::tuple
< size_type, size_type,
uint16_type > element_connectivity_type
Public Member Functions
size_type ad_first () const
size_type ad_second () const
uint16_type boundaryEntityDimension () const
edge_type const & edge (uint16_type i) const
edge_type & edge (uint16_type i)
edge_permutation_type edgePermutation (uint16_type i) const
edge_type const * edgePtr (uint16_type i) const
face_type const & face (uint16_type i) const
face_type & face (uint16_type i)
face_permutation_type facePermutation (uint16_type i) const
face_type const * facePtr (uint16_type i) const
std::pair< face_iterator,
face_iterator > faces ()
std::pair< face_const_iterator,
face_const_iterator > faces () const
GeoElement3D (size_type id=0)
GeoElement3D (GeoElement3D const &g)
size_type id () const
bool isGhostCell () const
bool isGhostFace () const
bool isInterProcessDomain () const
bool isOnBoundary () const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker3 const & marker3 () const
MeshBase const * mesh () const
GeoElement3D & operator= (GeoElement3D const &g)
size_type partition1 () const
size_type partition2 () const
face_permutation_type permutation (uint16_type i) const
uint16_type pos_first () const
uint16_type pos_second () const
uint16_type processId () const
void setEdge (uint16_type const i, edge_type const &p)
void setEdgePermutation (uint16_type i, edge_permutation_type o)
void setFace (uint16_type const i, face_type const &p)
void setFacePermutation (uint16_type i, face_permutation_type o)
~GeoElement3D ()
Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
void applyDisplacement (int i, ublas::vector< double > const &u)
void applyDisplacementG (int i, ublas::vector< double > const &u)
node_type barycenter () const
point_iterator beginPoint ()
point_const_iterator beginPoint () const
point_iterator endPoint ()
point_const_iterator endPoint () const
void exchangePoints (const uint16_type otn[numPoints])
node_type faceBarycenter (uint16_type f) const
matrix_node_type faceBarycenters () const
double faceMeasure (uint16_type f) const
std::vector< double > const & faceMeasures () const
PointType const & facePoint (uint16_type __f, uint16_type const __i) const
uint16_type faceToOppositePoint (uint16_type const _localFace, uint16_type const _point) const
matrix_node_type const & G () const
matrix_node_type & G ()
GeoND ()
GeoND (size_type id)
GeoND (GeoND const &e)
gm_ptrtype gm () const
return the geometric mapping if a mesh was set
gm1_ptrtype gm1 () const
return the geometric mapping if a mesh was set
double h () const
bool hasPoints () const
double hEdge (uint16_type f) const
double hFace (uint16_type f) const
bool isAnticlockwiseOriented () const
bool isNeighbor (self_type const &G) const
Marker1 const & marker () const
Marker1 & marker ()
Marker2 const & marker2 () const
Marker2 & marker2 ()
Marker3 const & marker3 () const
Marker3 & marker3 ()
double measure () const
value_type measurePointElementNeighbors () const
MeshBase const * mesh () const
std::pair< size_type,
size_type > const & neighbor (uint16_type n) const
uint16_type nNeighbors () const
uint16_type nOppositePointsPerFace () const
ublas::matrix_column
< matrix_node_type const > normal (uint16_type f) const
matrix_node_type const & normals () const
uint16_type nPoints () const
size_type numberOfPointElementNeighbors () const
permutation_type permutation (uint16_type) const
PointType & point (uint16_type i)
PointType const & point (uint16_type i) const
std::set< size_type > const & pointElementNeighborIds () const
PointType * pointPtr (uint16_type i)
PointType const * pointPtr (uint16_type i) const
PointType & reversepoint (uint16_type const i)
PointType const & reversepoint (uint16_type const i) const
void setMarker (flag_type v)
void setMarker2 (flag_type v)
void setMarker3 (flag_type v)
void setMeasurePointElementNeighbors (value_type meas)
set the measure of point element neighbors
void setMesh (MeshBase const *m) const
void setMeshAndGm (MeshBase const *m, gm_ptrtype const &gm, gm1_ptrtype const &gm1) const
void setNeighbor (uint16_type n, size_type neigh_id, size_type proc_id)
void setPoint (uint16_type const i, point_type const &p)
void setTags (std::vector< int > const &tags)
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
void swapPoints (const uint16_type &pt1, const uint16_type &pt2)
void update ()
void updateWithPc (typename gm_type::precompute_ptrtype const &pc, typename gm_type::faces_precompute_type &pcf)
matrix_node_type vertices () const
~GeoND ()
Public Member Functions inherited from Feel::GeoEntity< GEOSHAPE >
GeoEntity ()
GeoEntity (size_type i, size_type geometry=Geometry, size_type shape=Shape, size_type context=MESH_ENTITY_INTERNAL)
GeoEntity (GeoEntity const &__me)
GeoEntity & operator= (GeoEntity const &__me)
virtual ~GeoEntity ()
bool operator== (GeoEntity const &e) const
bool operator< (GeoEntity const &e) const
bool operator< (size_type __i) const
size_type id () const
uint16_type refDim () const
uint16_type nPoints () const
uint16_type nVertices () const
uint16_type nEdges () const
uint16_type nFaces () const
constexpr uint16_type nTopologicalFaces () const
uint16_type nGeometricFaces () const
uint16_type nNormals () const
bool hasShape (size_type __shape) const
bool isAVolume () const
bool isASurface () const
bool isALine () const
bool isAPoint () const
bool isAPointShape () const
bool isALineShape () const
bool isATriangleShape () const
bool isAQuadrangleShape () const
bool isATetrahedraShape () const
bool isAHexahedraShape () const
bool isLinear () const
bool isBilinear () const
bool isQuadratic () const
bool isInternal () const
bool isOnBoundary () const
uint16_type boundaryEntityDimension () const
bool isGhostCell () const
uint16_type processId () const
void setProcessId (uint16_type pid)
uint16_type pidInPartition () const
void setProcessIdInPartition (uint16_type pid)
uint16_type partitionId () const
uint16_type numberOfPartitions () const
size_type numberOfNeighborPartitions () const
bool isLinkedToOtherPartitions () const
std::vector< int > const & neighborPartitionIds () const
std::vector< int > & neighborPartitionIds ()
void clearNeighborPartitionIds ()
void setIdInOthersPartitions (uint16_type pid, size_type id)
size_type idInOthersPartitions (uint16_type pid) const
std::map< uint16_type,
size_type > const & idInOthersPartitions () const
void clearIdInOthersPartitions ()
bool active () const
void setId (size_type id)
void setOnBoundary (bool b, uint16_type ent_d=invalid_uint16_type_value)
void setNumberOfPartitions (uint16_type np)
void setNumberOfNeighborPartitions (uint16_type nep)
void setNeighborPartitionIds (std::vector< int > const &npids)
void addNeighborPartitionId (int p)
self_type & addElement (size_type e)
size_type numberOfElements () const
std::set< size_type > const & elements () const
std::set< size_type > & elements ()
self_type & addElementGhost (int proc, size_type e)
size_type numberOfProcGhost () const
std::map< int, std::set
< size_type > > const & elementsGhost () const
void clearElementsGhost ()
Public Member Functions inherited from Feel::SubFaceOfNone
boost::none_t element (uint16_type) const
bool isGhostFace (size_type p) const
bool isInterProcessDomain (size_type) const
size_type partition1 (size_type) const
size_type partition2 (size_type) const
SubFaceOfNone (SubFaceOfNone const &)
template<typename SFO >
SubFaceOfNone (SFO const &)
Static Public Attributes
static const uint16_type nDim = Dim
static const uint16_type numLocalEdges = super::numEdges
Number of local Edges (using Euler Formula)
static const uint16_type numLocalFaces = super::numFaces
Number of local Faces.
static const uint16_type numLocalVertices = super::numVertices
Number of local Vertices.
Static Public Attributes inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const int numEdges
static const int numFaces
static const uint16_type numLocalEdges
static const uint16_type numLocalPoints
static const uint16_type numLocalVertices
static const uint16_type numNeighbors
static const uint16_type numPoints
static const int numTopologicalFaces
static const uint16_type numVertices
static const size_type Shape
Static Public Attributes inherited from Feel::GeoEntity< GEOSHAPE >
static const size_type Shape
static const size_type Geometry
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const uint16_type numVertices
static const uint16_type numFaces
static const uint16_type numGeometricFaces
static const uint16_type numTopologicalFaces
static const uint16_type numEdges
static const uint16_type numNormals
static const uint16_type numPoints
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVolume
static const bool is_simplex
static const bool is_hypercube
Static Public Attributes inherited from Feel::SubFaceOfNone
static const uint16_type nDim = 1
Friends
class boost::serialization::access
Additional Inherited Members
Static Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, T, GeoElement0D< Dim, SubFaceOfNone, T > >
static uint16_type fToP (uint16_type const _localFace, uint16_type const _point)
Constructor & Destructor Documentation
template<uint16_type Dim, typename GEOSHAPE , typename T = double> Feel::GeoElement3D< Dim, GEOSHAPE, T >::GeoElement3D (size_type id = 0) inline explicit
Parameters
id identifier of the element
template<uint16_type Dim, typename GEOSHAPE , typename T = double> Feel::GeoElement3D< Dim, GEOSHAPE, T >::GeoElement3D (GeoElement3D< Dim, GEOSHAPE, T > const & g) inline
copy consttructor
template<uint16_type Dim, typename GEOSHAPE , typename T = double> Feel::GeoElement3D< Dim, GEOSHAPE, T >::~GeoElement3D () inline
destructor
Member Function Documentation
template<uint16_type Dim, typename GEOSHAPE , typename T = double> uint16_type Feel::GeoElement3D< Dim, GEOSHAPE, T >::boundaryEntityDimension () const inline
Returns
maximum dimension of the sub-entity touching the boundary of the element
References Feel::GeoEntity< GEOSHAPE >::boundaryEntityDimension().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> std::pair<face_iterator,face_iterator> Feel::GeoElement3D< Dim, GEOSHAPE, T >::faces () inline
Returns
the iterator pair (begin,end) of faces
template<uint16_type Dim, typename GEOSHAPE , typename T = double> std::pair<face_const_iterator,face_const_iterator> Feel::GeoElement3D< Dim, GEOSHAPE, T >::faces () const inline
Returns
the iterator pair (begin,end) of faces
template<uint16_type Dim, typename GEOSHAPE , typename T = double> size_type Feel::GeoElement3D< Dim, GEOSHAPE, T >::id () const inline
Returns
true if on the boundary, false otherwise
template<uint16_type Dim, typename GEOSHAPE , typename T = double> bool Feel::GeoElement3D< Dim, GEOSHAPE, T >::isGhostCell () const inline
Returns
true if ghost cell, false otherwise
References Feel::GeoEntity< GEOSHAPE >::isGhostCell().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> bool Feel::GeoElement3D< Dim, GEOSHAPE, T >::isInterProcessDomain () const inline
Returns
true if interprocess domain face, false otherwise
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> bool Feel::GeoElement3D< Dim, GEOSHAPE, T >::isOnBoundary () const inline
Returns
true if on the boundary, false otherwise
References Feel::GeoEntity< GEOSHAPE >::isOnBoundary().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> GeoElement3D& Feel::GeoElement3D< Dim, GEOSHAPE, T >::operator= (GeoElement3D< Dim, GEOSHAPE, T > const & g) inline
copy operator
template<uint16_type Dim, typename GEOSHAPE , typename T = double> size_type Feel::GeoElement3D< Dim, GEOSHAPE, T >::partition1 () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> size_type Feel::GeoElement3D< Dim, GEOSHAPE, T >::partition2 () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> uint16_type Feel::GeoElement3D< Dim, GEOSHAPE, T >::processId () const inline
Returns
process id
References Feel::GeoEntity< GEOSHAPE >::processId().
template<uint16_type Dim, typename GEOSHAPE , typename T = double> void Feel::GeoElement3D< Dim, GEOSHAPE, T >::setEdge (uint16_type const i, edge_type const & p) inline
Inserts an edge
References Feel::GeoElement3D< Dim, GEOSHAPE, T >::id(), and Feel::GeoElement3D< Dim, GEOSHAPE, T >::numLocalEdges.
template<uint16_type Dim, typename GEOSHAPE , typename T = double> void Feel::GeoElement3D< Dim, GEOSHAPE, T >::setFace (uint16_type const i, face_type const & p) inline
Inserts a face.