var searchData=
[
  ['d',['D',['../structFeel_1_1detail_1_1D.html',1,'Feel::detail']]],
  ['dar',['DAR',['../classFeel_1_1DAR.html',1,'Feel']]],
  ['datamap',['DataMap',['../classFeel_1_1DataMap.html',1,'Feel']]],
  ['dd',['DD',['../structFeel_1_1detail_1_1DD.html',1,'Feel::detail']]],
  ['ddmethod',['ddmethod',['../classFeel_1_1ddmethod.html',1,'Feel']]],
  ['debugstream',['DebugStream',['../classFeel_1_1DebugStream.html',1,'Feel']]],
  ['diff',['diff',['../structFeel_1_1inequalities_1_1diff.html',1,'Feel::inequalities']]],
  ['diff',['diff',['../structFeel_1_1functional_1_1diff.html',1,'Feel::functional']]],
  ['diff_5forder',['diff_order',['../structFeel_1_1diff__order.html',1,'Feel']]],
  ['dimfromshape',['DimFromShape',['../structFeel_1_1DimFromShape.html',1,'Feel']]],
  ['diode',['Diode',['../classDiode.html',1,'']]],
  ['directionalcomponentpointevaluation',['DirectionalComponentPointEvaluation',['../structFeel_1_1functional_1_1DirectionalComponentPointEvaluation.html',1,'Feel::functional']]],
  ['directionalcomponentpointsevaluation',['DirectionalComponentPointsEvaluation',['../structFeel_1_1functional_1_1DirectionalComponentPointsEvaluation.html',1,'Feel::functional']]],
  ['dirscalingmatrix',['DirScalingMatrix',['../classFeel_1_1DirScalingMatrix.html',1,'Feel']]],
  ['discontinuous',['Discontinuous',['../classFeel_1_1Discontinuous.html',1,'Feel']]],
  ['discontinuousinterfaces',['DiscontinuousInterfaces',['../classFeel_1_1DiscontinuousInterfaces.html',1,'Feel']]],
  ['div',['Div',['../structFeel_1_1detail_1_1Div.html',1,'Feel::detail']]],
  ['dof',['Dof',['../classFeel_1_1Dof.html',1,'Feel']]],
  ['dofcomposite',['DofComposite',['../classFeel_1_1DofComposite.html',1,'Feel']]],
  ['doftable',['DofTable',['../classFeel_1_1DofTable.html',1,'Feel']]],
  ['domain_5felement',['domain_element',['../structFeel_1_1OperatorLinear_1_1domain__element.html',1,'Feel::OperatorLinear']]],
  ['domain_5felement',['domain_element',['../structFeel_1_1OperatorLinearParametrized_1_1domain__element.html',1,'Feel::OperatorLinearParametrized']]],
  ['dualbasis',['DualBasis',['../classFeel_1_1DualBasis.html',1,'Feel']]],
  ['dualbasis_3c_20basis_20_3e',['DualBasis&lt; Basis &gt;',['../classFeel_1_1DualBasis.html',1,'Feel']]],
  ['dualbasis_3c_20mpl_3a_3aif_5f_3c_20mpl_3a_3abool_5f_3c_20convex_3c_20n_2c_201_2c_20n_20_3e_3a_3ais_5fsimplex_20_3e_2c_20mpl_3a_3aidentity_3c_20feel_3a_3adetail_3a_3aorthonormalpolynomialset_3c_20n_2c_201_2c_20realdim_2c_20polysettype_2c_20t_2c_20thetag_2c_20convex_20_3e_20_3e_2c_20mpl_3a_3aidentity_3c_20fem_3a_3adetail_3a_3arannacherturekpolynomialset_3c_20n_2c_20polysettype_2c_20t_20_3e_20_3e_20_3e_3a_3atype_3a_3atype_20_3e',['DualBasis&lt; mpl::if_&lt; mpl::bool_&lt; Convex&lt; N, 1, N &gt;::is_simplex &gt;, mpl::identity&lt; Feel::detail::OrthonormalPolynomialSet&lt; N, 1, RealDim, PolySetType, T, TheTAG, Convex &gt; &gt;, mpl::identity&lt; fem::detail::RannacherTurekPolynomialSet&lt; N, PolySetType, T &gt; &gt; &gt;::type::type &gt;',['../classFeel_1_1DualBasis.html',1,'Feel']]],
  ['dualbasis_3c_20nedelecpolynomialset_3c_20n_2c_20o_2c_20t_2c_20convex_20_3e_20_3e',['DualBasis&lt; NedelecPolynomialSet&lt; N, O, T, Convex &gt; &gt;',['../classFeel_1_1DualBasis.html',1,'Feel']]],
  ['dualbasis_3c_20raviartthomaspolynomialset_3c_20n_2c_20o_2c_20t_2c_20convex_20_3e_20_3e',['DualBasis&lt; RaviartThomasPolynomialSet&lt; N, O, T, Convex &gt; &gt;',['../classFeel_1_1DualBasis.html',1,'Feel']]],
  ['dubiner',['Dubiner',['../classFeel_1_1Dubiner.html',1,'Feel']]],
  ['dubiner_3c_20dim_2c_20order_2c_20normalized_3c_20false_20_3e_2c_20t_2c_20storageublas_20_3e',['Dubiner&lt; Dim, Order, Normalized&lt; false &gt;, T, StorageUBlas &gt;',['../classFeel_1_1Dubiner.html',1,'Feel']]],
  ['dubinertag',['DubinerTag',['../structFeel_1_1DubinerTag.html',1,'Feel']]],
  ['dubinertraits',['DubinerTraits',['../structFeel_1_1DubinerTraits.html',1,'Feel']]],
  ['dummy_5fdata',['dummy_data',['../structFeel_1_1dummy__data.html',1,'Feel']]]
];
